import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";


// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const BrieflyAI = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="UpSum.ai Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Speed Up Your Content Consumption with UpSum.ai
                </p>
                <h3>Customizable, Copyright-Free Summaries Tailored to You</h3>
              </div>
              {[
                {
                  icon: "⚡",
                  title: "Instant Summarization",
                  desc: "UpSum.ai quickly condenses long documents, reports, or articles into clear, concise summaries in seconds, giving you a faster way to digest information.",
                },
                {
                  icon: "🛠️",
                  title: "Fully Customizable Content",
                  desc: "Adjust the depth, tone, and style of summaries to suit your personal, academic, or professional needs, all without copyright concerns.",
                },
                {
                  icon: "🌐",
                  title: "Multilingual Support",
                  desc: "UpSum.ai can summarize content in multiple languages, making it accessible to a global audience.",
                },
                {
                  icon: "✅",
                  title: "No Copyright Concerns",
                  desc: "All summaries generated by UpSum.ai are original and copyright-free, ensuring you can use them without any legal issues.",
                },
                {
                  icon: "🧠",
                  title: "AI-Driven Precision",
                  desc: "UpSum.ai utilizes cutting-edge AI algorithms to ensure that summaries are accurate and meaningful, providing clarity on complex content.",
                },
                {
                  icon: "📚",
                  title: "Ideal for Professionals & Researchers",
                  desc: "UpSum.ai is designed for students, researchers, and professionals who need precise summaries without missing key details, saving you valuable time.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is UpSum.ai?",
                  a: "UpSum.ai is an AI-powered tool that generates customizable, copyright-free summaries, adapting to your needs for academic, business, or casual use.",
                },
                {
                  q: "How does UpSum.ai work?",
                  a: "UpSum.ai uses advanced algorithms to summarize content, adjusting length, tone, and structure based on your input, ensuring the results are tailored to your needs.",
                },
                {
                  q: "Can UpSum.ai adjust content based on my preferences?",
                  a: "Yes, UpSum.ai adapts its summaries to your preferences, customizing tone, depth, and length, whether you need a brief overview or detailed analysis.",
                },
                {
                  q: "Is UpSum.ai content free from copyright restrictions?",
                  a: "Yes, all summaries generated by UpSum.ai are original and copyright-free, ensuring you can use, share, and publish them without concerns about plagiarism.",
                },
                {
                  q: "Can UpSum.ai summarize large documents?",
                  a: "Yes, UpSum.ai efficiently summarizes long and complex documents, making them easier to read and understand.",
                },
                {
                  q: "Does UpSum.ai support multiple document formats?",
                  a: "Yes, UpSum.ai supports various formats like PDFs, Word documents, and plain text files.",
                },
                {
                  q: "Is UpSum.ai free to use?",
                  a: "UpSum.ai offers both a free version with basic features and a paid subscription that unlocks advanced features like unlimited summaries, customizations, and more export options.",
                },
                {
                  q: "Can I export content from UpSum.ai?",
                  a: "Yes, you can export summaries in formats like text files, PDFs, or others depending on your subscription plan.",
                },
                {
                  q: "Can I use UpSum.ai for academic purposes?",
                  a: "Absolutely, UpSum.ai is highly suitable for summarizing academic papers, research articles, and textbooks.",
                },
                {
                  q: "How accurate are the summaries generated by UpSum.ai?",
                  a: "UpSum.ai provides highly accurate summaries, focusing on key concepts and adapting to the context of the input material.",
                },
                {
                  q: "Does UpSum.ai support content rewriting or paraphrasing?",
                  a: "UpSum.ai specializes in summarization and does not focus on rewriting or paraphrasing, but its summaries are clear and concise.",
                },
                {
                  q: "Can I use UpSum.ai without technical expertise?",
                  a: "Yes, UpSum.ai is designed for users of all backgrounds with an intuitive, user-friendly interface.",
                },
                {
                  q: "What types of content can I summarize with UpSum.ai?",
                  a: "You can summarize various content types, including academic papers, business reports, articles, and personal writing.",
                },
                {
                  q: "Is UpSum.ai suitable for professional use?",
                  a: "Yes, UpSum.ai is ideal for professionals who need to summarize business documents, technical reports, and complex materials.",
                },
                {
                  q: "Can I customize the tone of the output in UpSum.ai?",
                  a: "Yes, you can adjust the tone of the summary to be formal, casual, or technical, depending on your needs.",
                },
                {
                  q: "Does UpSum.ai store my content?",
                  a: "UpSum.ai processes your content temporarily for summarization and does not store or share your data after the process.",
                },
                {
                  q: "Can I collaborate with others on content using UpSum.ai?",
                  a: "While UpSum.ai doesn’t have built-in collaboration tools, you can easily share exported summaries with others for review and feedback.",
                },
                {
                  q: "Is the content from UpSum.ai plagiarism-free?",
                  a: "Yes, UpSum.ai generates original and plagiarism-free summaries based on your input content.",
                },
                {
                  q: "Can I expand content using UpSum.ai?",
                  a: "UpSum.ai specializes in summarization and does not expand or add additional information to the original content.",
                },
                {
                  q: "How fast is UpSum.ai in generating summaries?",
                  a: "UpSum.ai generates summaries quickly, typically within seconds, depending on content complexity.",
                },
                {
                  q: "Does UpSum.ai require installation?",
                  a: "No, UpSum.ai is a web-based tool that works across all modern browsers, requiring no installation.",
                },
                {
                  q: "What makes UpSum.ai different from other summarization tools?",
                  a: "UpSum.ai stands out for its adaptability, customization options, and copyright-free summaries, making it ideal for a range of use cases.",
                },
                {
                  q: "Does UpSum.ai have a mobile version?",
                  a: "While UpSum.ai is web-based, it is fully responsive and can be accessed on mobile browsers.",
                },
                {
                  q: "Can I use UpSum.ai for business content?",
                  a: "Yes, UpSum.ai is perfect for summarizing business reports, technical documents, market analysis, and more.",
                },
                {
                  q: "Where can I get support for UpSum.ai?",
                  a: "You can find support through UpSum.ai’s website, including FAQs, help guides, and contact options for direct assistance.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src="https://www.testingcatalog.com/content/images/size/w2000/2024/06/screenshot-app.runwayml.com-2024.06.24-00_36_32--1-.png"
                alt=""
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src="https://www.techspot.com/articles-info/2720/images/2023-08-17-image.jpg"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>UpSum.ai</strong> is the Go-To Tool for
                    Customizable, Copyright-Free Summarization
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>UpSum.ai</strong> transforms the process of
                    summarizing content by providing adaptable, copyright-free
                    summaries tailored to your specific needs. Whether you’re
                    drafting academic papers, business reports, or creative
                    works, here’s why UpSum.ai is your best choice:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>User-Centric Summaries:</strong> UpSum.ai
                      customizes the length, tone, and structure of the summary
                      based on your preferences, ensuring it meets your needs,
                      whether for a concise overview or an in-depth summary.
                    </li>
                    <li className="mb-3">
                      <strong>Highly Adaptable:</strong> UpSum.ai is versatile,
                      handling various content types, from research papers to
                      blog posts, providing summaries that suit any subject
                      matter.
                    </li>
                    <li className="mb-3">
                      <strong>Copyright-Free Content:</strong> Every summary
                      generated is completely copyright-free, allowing you to
                      use, share, or publish the content without any legal
                      concerns.
                    </li>
                    <li className="mb-3">
                      <strong>Fast and Efficient:</strong> UpSum.ai generates
                      summaries in seconds, helping you save time while ensuring
                      that content quality remains intact.
                    </li>
                    <li className="mb-3">
                      <strong>Supports Various Content Types:</strong> From
                      articles to reports, UpSum.ai easily handles multiple
                      types of content, delivering high-quality summaries every
                      time.
                    </li>
                    <li className="mb-3">
                      <strong>Flexible Output Options:</strong> With multiple
                      customization settings, UpSum.ai allows you to choose the
                      best format for your needs, whether for academic,
                      professional, or personal use.
                    </li>
                    <li className="mb-3">
                      <strong>Intuitive and Easy to Use:</strong> The simple and
                      clean interface makes it easy for users of all levels to
                      quickly summarize content without any hassle.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Start Using <strong>UpSum.ai</strong> — Smart, Custom
                      Summaries for Every Need
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>UpSum.ai</strong> is a Dynamic and Copyright-Free AI
              Summarization Tool
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>UpSum.ai</strong> adapts its summaries based on your input
              and preferences, delivering custom, copyright-free content suited
              for academic, business, or casual needs—without compromising
              originality or clarity.
            </p>
            <div className="row justify-content-center gap-2">
              {/* Pros Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">✅ Pros</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Copyright-Free Content:</strong> All outputs from
                    UpSum.ai are safe to use, share, or publish without any
                    copyright concerns.
                  </li>
                  <li className="mb-2">
                    <strong>Dynamic Summarization:</strong> UpSum.ai tailors its
                    summaries based on the user's input and goals—whether
                    academic, business, or casual—adjusting tone and detail
                    accordingly.
                  </li>
                  <li className="mb-2">
                    <strong>Intuitive Interface:</strong> The user-friendly UI
                    ensures that anyone can easily input text and receive
                    customized summaries quickly.
                  </li>
                  <li className="mb-2">
                    <strong>Fast Output:</strong> Delivers clear and concise
                    summaries in seconds, boosting productivity for users in
                    various fields.
                  </li>
                  <li className="mb-2">
                    <strong>Versatile Content Support:</strong> Works with
                    various content formats, including articles, blogs, reports,
                    and research papers.
                  </li>
                </ul>
              </div>

              {/* Cons Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">⚠️ Cons</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Limited Academic Features:</strong> Not specifically
                    designed for academic needs like citations or complex
                    referencing.
                  </li>
                  <li className="mb-2">
                    <strong>Paraphrasing May Require Adjustment:</strong> While
                    the tone adapts well, more complex rewrites may need further
                    refinement by the user.
                  </li>
                  <li className="mb-2">
                    <strong>No Offline Functionality:</strong> Requires an
                    active internet connection, as there is no desktop or
                    offline version available.
                  </li>
                  <li className="mb-2">
                    <strong>Advanced Features May Be Restricted:</strong> Some
                    advanced features or export options may be available only to
                    premium users or with a paid account.
                  </li>
                  <li className="mb-2">
                    <strong>Lack of Collaborative Tools:</strong> Does not
                    include integrated features for team collaboration, such as
                    shared workspaces or comments.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover Leading Alternatives to Resoomer AI for Summarization and
              Content Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Resoomer AI</strong> excels at summarizing and
              refining content, several other platforms offer unique
              capabilities for text analysis, summarization, and rewriting,
              helping creators produce concise, high-quality, and original
              content effortlessly.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>UpSum.ai</strong>: Provides adaptive summarization
                    that changes according to your input, topic, and
                    purpose—whether academic, technical, or casual. Its
                    summaries are completely copyright-free, customizable, and
                    can be freely reused in any form.
                  </li>
                  <li className="mb-2">
                    <strong>Resoomer AI</strong>: Specializes in summarizing and
                    refining large bodies of text, ensuring clear and concise
                    content while preserving the original message. You can
                    customize the summaries to suit your needs.
                  </li>
                  <li className="mb-2">
                    <strong>SMMRY AI</strong>: Allows users to generate
                    copyright-free summaries with control over the content’s
                    length and focus. It adapts to your preferences, offering
                    flexibility without compromising originality or ownership.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeBot AI</strong>: An adaptable AI tool that
                    tailors summaries to your specifications, providing
                    copyright-free content without losing key context. You can
                    customize the length, tone, and key points to match your
                    needs.
                  </li>
                  <li className="mb-2">
                    <strong>Scholarcy</strong>: Ideal for academic and technical
                    content, Scholarcy automatically highlights key facts and
                    arguments, offering a fully customizable and copyright-free
                    tool. Perfect for researchers, students, and content
                    reviewers.
                  </li>
                  <li className="mb-2">
                    <strong>QuillBot</strong>: Offers AI-powered writing
                    enhancements, including paraphrasing and summarization
                    tools, helping users improve writing quality and create
                    concise content.
                  </li>
                  <li className="mb-2">
                    <strong>Text Summarizer</strong>: A straightforward online
                    tool that condenses large texts into essential points,
                    perfect for research or study purposes.
                  </li>
                  <li className="mb-2">
                    <strong>Copy.ai</strong>: An AI-powered writing tool that
                    aids in generating marketing copy, blog posts, and other
                    content, with summarizing and refining capabilities to
                    improve clarity and engagement.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeThis</strong>: A simple, effective AI tool
                    for summarizing text, helping users quickly grasp the
                    essence of content without reading the entire document.
                  </li>
                  <li className="mb-2">
                    <strong>TLDR This</strong>: Focuses on creating quick,
                    readable summaries from large articles, papers, and
                    documents, perfect for saving time while capturing key
                    points.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
          <div className=" row d-flex align-items-center justify-content-between mb-1">
            {/* Left side (Text Section) */}
            <div
              style={{ flex: 1, paddingRight: "30px" }}
              className="col-6 col-md-12 "
            >
              <p className="text-primary">Write better, faster</p>
              <h1>Briefly AI:</h1>
              <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
              <p>
                Briefly AI is an advanced AI-powered content summarization tool
                designed to help users quickly summarize long-form content into
                concise briefs. It is ideal for writers, students, researchers,
                content creators, journalists, marketers, and anyone needing to
                distill large volumes of information into digestible formats.
              </p>

              <div className="mb-3">
                <a
                                 href="https://www.brieflyai.com"
                                 rel="noopener noreferrer"
                                 className="btn btn-primary me-2"
                               >
                                 Explore Tool
                               </a>
              </div>
            </div>

            {/* Right side (Image Section) */}
            <div
              style={{
                flex: 1,
                textAlign: "center",
                Width: "100%",
                height: "250px",
              }}
              className="col-6 col-md-12 mb-5  "
            >
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
                style={{ MaxWidth: "100%", height: "300px" }}
              />
            </div>
          </div>

          <section style={{ backgroundColor: "#1b1f2b", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Your Smart Summarizer for Research and Technical Content
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                See How UpSum.ai Delivers Tailored Summaries, Instantly and
                Without Restrictions
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                UpSum.ai turns complex research, articles, and documentation
                into personalized, easy-to-digest summaries—designed for your
                needs and copyright-free.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .upsum-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Capture Critical Points in Seconds
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      UpSum.ai quickly scans your text and pinpoints essential
                      ideas, methods, and results—saving you hours of reading.
                    </p>
                    <div className="upsum-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .upsum-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Control What and How It Summarizes
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Choose to emphasize conclusions, figures, or citations.
                      UpSum.ai adapts the structure to match your academic,
                      business, or personal goals.
                    </p>
                    <div className="upsum-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .upsum-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Use Freely—No Copyright Limitations
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      UpSum.ai generates summaries that are free from copyright
                      concerns, allowing you to reuse them in reports, blogs,
                      and study guides with peace of mind.
                    </p>
                    <div className="upsum-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          <div className="bg-primary text-center text-light rounded-4 p-5 mt-5">
            <h4 className="mb-3">Ready to get started with BrieflyAI?</h4>
            <p className="mb-4">
              Join thousands of professionals already boosting their
              productivity!
            </p>
            <div>
              <button className="btn btn-light me-3">Try Now for Free</button>
              <button className="btn btn-outline-light">Schedule a Demo</button>
            </div>
            <small className="d-block mt-2">
              No credit card required. 14-day free trial available.
            </small>
          </div>
        </div>
      </div>
    </>
  );
};

export default BrieflyAI;
