import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const HumataAI = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="Humata AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Speed Up Your Content Customization with Humata AI
                </p>
                <h3>
                  Customizable, Copyright-Free Paraphrasing Tailored to You
                </h3>
              </div>
              {[
                {
                  icon: "⚡",
                  title: "Instant Paraphrasing",
                  desc: "Humata AI quickly rephrases long documents, reports, or articles into clear, concise versions in seconds, providing a faster way to rewrite content.",
                },
                {
                  icon: "🛠️",
                  title: "Fully Customizable Content",
                  desc: "Adjust the depth, tone, and style of paraphrased content to suit your personal, academic, or professional needs, all without copyright concerns.",
                },
                {
                  icon: "🌐",
                  title: "Multilingual Support",
                  desc: "Humata AI can rephrase content in multiple languages, making it accessible to a global audience.",
                },
                {
                  icon: "✅",
                  title: "No Copyright Concerns",
                  desc: "All paraphrases generated by Humata AI are original and copyright-free, ensuring you can use them without any legal issues.",
                },
                {
                  icon: "🧠",
                  title: "AI-Driven Precision",
                  desc: "Humata AI utilizes cutting-edge AI algorithms to ensure that paraphrases are accurate and meaningful, providing clarity on complex content.",
                },
                {
                  icon: "📚",
                  title: "Ideal for Professionals & Researchers",
                  desc: "Humata AI is designed for students, researchers, and professionals who need precise paraphrasing without missing key details, saving you valuable time.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is Humata AI?",
                  a: "Humata AI is an AI-powered tool that generates customizable, copyright-free paraphrases, adapting to your needs for academic, business, or casual use.",
                },
                {
                  q: "How does Humata AI work?",
                  a: "Humata AI uses advanced algorithms to paraphrase content, adjusting length, tone, and structure based on your input, ensuring the results are tailored to your needs.",
                },
                {
                  q: "Can Humata AI adjust content based on my preferences?",
                  a: "Yes, Humata AI adapts its paraphrases to your preferences, customizing tone, depth, and length, whether you need a brief overview or detailed analysis.",
                },
                {
                  q: "Is Humata AI content free from copyright restrictions?",
                  a: "Yes, all paraphrases generated by Humata AI are original and copyright-free, ensuring you can use, share, and publish them without concerns about plagiarism.",
                },
                {
                  q: "Can Humata AI handle large documents?",
                  a: "Yes, Humata AI efficiently paraphrases long and complex documents, making them easier to read and understand.",
                },
                {
                  q: "Does Humata AI support multiple document formats?",
                  a: "Yes, Humata AI supports various formats like PDFs, Word documents, and plain text files.",
                },
                {
                  q: "Is Humata AI free to use?",
                  a: "Humata AI offers both a free version with basic features and a paid subscription that unlocks advanced features like unlimited paraphrasing, customizations, and more export options.",
                },
                {
                  q: "Can I export content from Humata AI?",
                  a: "Yes, you can export paraphrased content in formats like text files, PDFs, or others depending on your subscription plan.",
                },
                {
                  q: "Can I use Humata AI for academic purposes?",
                  a: "Absolutely, Humata AI is highly suitable for paraphrasing academic papers, research articles, and textbooks.",
                },
                {
                  q: "How accurate are the paraphrases generated by Humata AI?",
                  a: "Humata AI provides highly accurate paraphrases, focusing on key concepts and adapting to the context of the input material.",
                },
                {
                  q: "Does Humata AI support content rewriting?",
                  a: "Humata AI specializes in paraphrasing and does not focus on rewriting, but its paraphrases are clear and concise.",
                },
                {
                  q: "Can I use Humata AI without technical expertise?",
                  a: "Yes, Humata AI is designed for users of all backgrounds with an intuitive, user-friendly interface.",
                },
                {
                  q: "What types of content can I paraphrase with Humata AI?",
                  a: "You can paraphrase various content types, including academic papers, business reports, articles, and personal writing.",
                },
                {
                  q: "Is Humata AI suitable for professional use?",
                  a: "Yes, Humata AI is ideal for professionals who need to paraphrase business documents, technical reports, and complex materials.",
                },
                {
                  q: "Can I customize the tone of the output in Humata AI?",
                  a: "Yes, you can adjust the tone of the paraphrased text to be formal, casual, or technical, depending on your needs.",
                },
                {
                  q: "Does Humata AI store my content?",
                  a: "Humata AI processes your content temporarily for paraphrasing and does not store or share your data after the process.",
                },
                {
                  q: "Can I collaborate with others on content using Humata AI?",
                  a: "While Humata AI doesn’t have built-in collaboration tools, you can easily share exported paraphrases with others for review and feedback.",
                },
                {
                  q: "Is the content from Humata AI plagiarism-free?",
                  a: "Yes, Humata AI generates original and plagiarism-free paraphrases based on your input content.",
                },
                {
                  q: "Can I expand content using Humata AI?",
                  a: "Humata AI specializes in paraphrasing and does not expand or add additional information to the original content.",
                },
                {
                  q: "How fast is Humata AI in generating paraphrases?",
                  a: "Humata AI generates paraphrases quickly, typically within seconds, depending on content complexity.",
                },
                {
                  q: "Does Humata AI require installation?",
                  a: "No, Humata AI is a web-based tool that works across all modern browsers, requiring no installation.",
                },
                {
                  q: "What makes Humata AI different from other paraphrasing tools?",
                  a: "Humata AI stands out for its adaptability, customization options, and copyright-free paraphrasing, making it ideal for a range of use cases.",
                },
                {
                  q: "Does Humata AI have a mobile version?",
                  a: "While Humata AI is web-based, it is fully responsive and can be accessed on mobile browsers.",
                },
                {
                  q: "Can I use Humata AI for business content?",
                  a: "Yes, Humata AI is perfect for paraphrasing business reports, technical documents, market analysis, and more.",
                },
                {
                  q: "Where can I get support for Humata AI?",
                  a: "You can find support through Humata AI’s website, including FAQs, help guides, and contact options for direct assistance.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src="https://www.testingcatalog.com/content/images/size/w2000/2024/06/screenshot-app.runwayml.com-2024.06.24-00_36_32--1-.png"
                alt=""
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src="https://www.techspot.com/articles-info/2720/images/2023-08-17-image.jpg"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>Humata AI</strong> is the Ideal Tool for
                    Customizable, Copyright-Free Paraphrasing
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>Humata AI</strong> revolutionizes the paraphrasing
                    process by providing adaptable, copyright-free content
                    tailored to your specific needs. Whether you're working on
                    academic papers, business reports, or creative writing,
                    here’s why Humata AI is the right choice:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>User-Centric Paraphrasing:</strong> Humata AI
                      customizes the content’s structure, tone, and complexity
                      to meet your requirements, ensuring that the paraphrased
                      text fits your needs perfectly, whether for clarity or
                      depth.
                    </li>
                    <li className="mb-3">
                      <strong>Highly Versatile:</strong> Humata AI works
                      seamlessly with various content types, from research
                      papers to blog posts, providing tailored paraphrases that
                      suit any subject matter.
                    </li>
                    <li className="mb-3">
                      <strong>Copyright-Free Output:</strong> Every paraphrase
                      generated by Humata AI is 100% copyright-free, meaning you
                      can use, share, or publish the content without worrying
                      about legal issues.
                    </li>
                    <li className="mb-3">
                      <strong>Fast and Efficient:</strong> Humata AI provides
                      paraphrased content in just seconds, saving you time while
                      maintaining high-quality, original results.
                    </li>
                    <li className="mb-3">
                      <strong>Supports Various Content Types:</strong> From
                      articles to reports, Humata AI effectively handles
                      multiple content formats, ensuring high-quality output
                      every time.
                    </li>
                    <li className="mb-3">
                      <strong>Flexible Output Options:</strong> With a wide
                      range of customization settings, Humata AI lets you choose
                      the ideal format for your needs, whether for academic,
                      professional, or casual use.
                    </li>
                    <li className="mb-3">
                      <strong>Intuitive and Easy to Use:</strong> The clean,
                      user-friendly interface makes it easy for users of all
                      levels to paraphrase content without any difficulty.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Start Using <strong>Humata AI</strong> — Effortless,
                      Custom Paraphrasing for Every Need
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>Humata AI</strong> is an Effective and Copyright-Free
              Paraphrasing Tool
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>Humata AI</strong> adapts its paraphrased content
              according to your input, ensuring unique, copyright-free outputs
              that maintain the original meaning, making it ideal for academic,
              business, and casual use.
            </p>
            <div className="row justify-content-center gap-2">
              {/* Pros Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">✅ Pros</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Copyright-Free Content:</strong> All outputs from
                    Humata AI are completely copyright-free, allowing you to
                    use, share, or publish them without any concerns.
                  </li>
                  <li className="mb-2">
                    <strong>Content Customization:</strong> The tool adjusts the
                    paraphrased text based on your needs, whether for academic,
                    business, or casual use, while retaining the original
                    meaning.
                  </li>
                  <li className="mb-2">
                    <strong>User-Friendly Interface:</strong> The
                    easy-to-navigate interface makes it simple for users to
                    input text and get the required paraphrased results quickly.
                  </li>
                  <li className="mb-2">
                    <strong>Speedy Results:</strong> Delivers paraphrased
                    content almost instantly, enhancing efficiency for users
                    across different industries.
                  </li>
                  <li className="mb-2">
                    <strong>Works with Various Content Types:</strong> Ideal for
                    a wide range of text types, including articles, blogs,
                    reports, and academic papers.
                  </li>
                </ul>
              </div>

              {/* Cons Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">⚠️ Cons</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Limited Academic Features:</strong> Not designed to
                    handle advanced academic requirements like citations or
                    complex references.
                  </li>
                  <li className="mb-2">
                    <strong>May Require User Refinement:</strong> While
                    paraphrased content is adaptable, some complex texts may
                    require further refinement for complete clarity or tone.
                  </li>
                  <li className="mb-2">
                    <strong>Online-Only Tool:</strong> Humata AI is not
                    available offline and requires an active internet connection
                    to function.
                  </li>
                  <li className="mb-2">
                    <strong>Advanced Features are Premium:</strong> Some
                    advanced options, like enhanced paraphrasing features or
                    export functionality, may be limited to paid accounts.
                  </li>
                  <li className="mb-2">
                    <strong>Lack of Collaboration Tools:</strong> Humata AI
                    doesn’t have integrated tools for collaboration, such as
                    shared documents or team comments.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover Leading Alternatives to Humata AI for Paraphrasing and
              Content Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Humata AI</strong> excels at transforming text into
              unique, original content, several other platforms offer
              specialized capabilities for paraphrasing, rewriting, and content
              refinement—helping creators produce high-quality and
              copyright-free content effortlessly.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Humata AI</strong>: Specializes in rephrasing and
                    paraphrasing content to ensure uniqueness, while maintaining
                    the original meaning. It’s customizable and ideal for a
                    variety of purposes—academic, business, or casual—while
                    being completely copyright-free.
                  </li>
                  <li className="mb-2">
                    <strong>UpSum.ai</strong>: Provides adaptive summarization
                    based on your input, tailoring content to fit academic,
                    technical, or casual needs. Its summaries are fully
                    customizable and copyright-free, allowing for unlimited
                    reuse.
                  </li>
                  <li className="mb-2">
                    <strong>Resoomer AI</strong>: Known for summarizing long
                    texts into concise formats, Resoomer offers easy
                    customization options to tailor summaries to specific needs,
                    keeping the core message intact.
                  </li>
                  <li className="mb-2">
                    <strong>SMMRY AI</strong>: Lets users control the length and
                    focus of their summaries, providing copyright-free content
                    that adapts to user preferences without sacrificing
                    originality.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeBot AI</strong>: This adaptable tool allows
                    for summary customization in terms of length, tone, and
                    emphasis, ensuring that the paraphrased or summarized
                    content is suitable for various needs while remaining
                    copyright-free.
                  </li>
                  <li className="mb-2">
                    <strong>Scholarcy</strong>: Ideal for academic and
                    research-focused content, Scholarcy highlights key facts and
                    arguments, offering a fully customizable and copyright-free
                    paraphrasing tool for researchers and students.
                  </li>
                  <li className="mb-2">
                    <strong>QuillBot</strong>: An AI-powered writing enhancement
                    tool, QuillBot includes paraphrasing and summarization
                    features that help improve text quality and generate
                    concise, original content.
                  </li>
                  <li className="mb-2">
                    <strong>Text Summarizer</strong>: A simple tool for
                    condensing large texts into key points, Text Summarizer is
                    perfect for research, study materials, or quick content
                    consumption.
                  </li>
                  <li className="mb-2">
                    <strong>Copy.ai</strong>: Designed to help with writing
                    content such as marketing copy, blog posts, and more,
                    Copy.ai offers paraphrasing and content refinement
                    capabilities to enhance clarity and engagement.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeThis</strong>: A user-friendly AI tool that
                    condenses texts into short, clear summaries, ideal for
                    quickly extracting key insights from content.
                  </li>
                  <li className="mb-2">
                    <strong>TLDR This</strong>: Focuses on producing quick,
                    digestible summaries from large documents, papers, or
                    articles, saving users time while ensuring key points are
                    captured.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
          <div className=" row d-flex align-items-center justify-content-between mb-1">
            {/* Left side (Text Section) */}
            <div
              style={{ flex: 1, paddingRight: "30px" }}
              className="col-6 col-md-12 "
            >
              <p className="text-primary">Write better, faster</p>
              <h1>Humata AI:</h1>
              <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
              <p>
                Humata AI is a state-of-the-art artificial intelligence tool
                designed to revolutionize the way we interact with textual
                content. It leverages advanced natural language processing (NLP)
                algorithms to read, understand, and extract useful information
                from a wide variety of document types, such as PDFs, legal
                documents, research papers, academic papers, technical manuals,
                and more. Whether you need to summarize lengthy reports, extract
                specific data points, or generate insights, Humata AI provides a
                solution that saves time and effort.
              </p>

              <div className="mb-3">
                <span className="badge bg-primary me-2">Image Generation</span>
                <span className="badge bg-success me-2">Creative</span>
                <span className="badge bg-warning text-dark">Paid</span>
              </div>
            </div>

            {/* Right side (Image Section) */}
            <div
              style={{
                flex: 1,
                textAlign: "center",
                Width: "100%",
                height: "250px",
              }}
              className="col-6 col-md-12 mb-5  "
            >
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
                style={{ MaxWidth: "100%", height: "300px" }}
              />
            </div>
          </div>

          <section style={{ backgroundColor: "#1b1f2b", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Your Smart Paraphrasing Tool for Research and Content Creation
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                See How Humata AI Transforms Your Content, Instantly and Without
                Restrictions
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                Humata AI helps you rephrase complex text, articles, and
                documentation into unique, original content—designed to fit your
                style and free from copyright issues.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .humata-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Rephrase in Seconds
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Humata AI instantly rephrases your text, maintaining its
                      meaning while ensuring unique content.
                    </p>
                    <div className="humata-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .humata-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Tailor Your Rephrasing Style
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Customize the tone, structure, and complexity of your
                      paraphrased text to suit your needs, whether for formal,
                      casual, or technical purposes.
                    </p>
                    <div className="humata-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0b6d63",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .humata-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #4ce1b6;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      No Copyright Issues
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Humata AI creates paraphrased text that is original,
                      copyright-free, and ready to be used in any format.
                    </p>
                    <div className="humata-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          <div className="bg-primary text-center text-light rounded-4 p-5 mt-5">
            <h4 className="mb-3">Ready to get started with HumataAI?</h4>
            <p className="mb-4">
              Join thousands of professionals already boosting their
              productivity!
            </p>
            <div>
              <button className="btn btn-light me-3">Try Now for Free</button>
              <button className="btn btn-outline-light">Schedule a Demo</button>
            </div>
            <small className="d-block mt-2">
              No credit card required. 14-day free trial available.
            </small>
          </div>
        </div>
      </div>
    </>
  );
};

export default HumataAI;
