import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";
import resoomerSS1 from '../../../../public/assets/Img/AI for Document/resoomerSS1.png';
import resoomerSS2 from '../../../../public/assets/Img/AI for Document/resoomerSS2.png';


// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const Resoomer = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="Resoomer AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Enhance Your Productivity with Resoomer AI
                </p>
                <h3>
                  Customizable, Copyright-Free Content Generated Instantly
                </h3>
              </div>
              {[
                {
                  icon: "🧠",
                  title: "AI-Powered Summarization",
                  desc: "Resoomer AI condenses long documents into digestible summaries while preserving essential ideas, saving you time and effort.",
                },
                {
                  icon: "✍️",
                  title: "Content Rewriting Made Simple",
                  desc: "Transform your content with ease—rephrase, rewrite, or expand text while maintaining clarity and meaning.",
                },
                {
                  icon: "🎯",
                  title: "Adaptable Tone & Style",
                  desc: "Customize the tone and complexity of the output to suit academic, professional, or casual use cases.",
                },
                {
                  icon: "🌐",
                  title: "Multilingual Support",
                  desc: "Resoomer AI supports content generation in multiple languages, making it a versatile tool for global users.",
                },
                {
                  icon: "🛡️",
                  title: "Copyright-Free Output",
                  desc: "All content generated by Resoomer AI is original and copyright-free, making it safe for commercial and personal use.",
                },
                {
                  icon: "🤖",
                  title: "Smart AI Suggestions",
                  desc: "Receive real-time suggestions to enhance and improve your text based on your goals and context.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is Resoomer AI?",
                  a: "Resoomer AI is a powerful AI-based summarization and content adaptation tool that helps users condense and transform text into customized, copyright-free content.",
                },
                {
                  q: "How does Resoomer AI work?",
                  a: "Resoomer AI analyzes your text input and uses artificial intelligence to summarize, rephrase, or expand it based on your chosen preferences, such as tone, length, and complexity.",
                },
                {
                  q: "Can Resoomer AI modify content according to my needs?",
                  a: "Yes, Resoomer AI allows you to customize how your content is generated by letting you control parameters like tone, style, structure, and depth.",
                },
                {
                  q: "Is Resoomer AI content copyright-free?",
                  a: "Yes, Resoomer AI generates original content that is free of copyright, making it safe for personal, educational, or commercial use.",
                },
                {
                  q: "Can Resoomer AI summarize long documents?",
                  a: "Absolutely! Resoomer AI is designed to quickly summarize lengthy documents into clear and concise summaries while preserving key points.",
                },
                {
                  q: "Does Resoomer AI support multiple languages?",
                  a: "Yes, Resoomer AI supports various languages, allowing users to summarize and adapt content in multiple global languages.",
                },
                {
                  q: "Is Resoomer AI free to use?",
                  a: "Resoomer AI offers a free plan with essential features. Premium subscriptions are available for advanced tools and customization.",
                },
                {
                  q: "Can I export the content generated by Resoomer AI?",
                  a: "Yes, you can export generated content in formats like TXT, DOCX, and PDF, making it easy to integrate into your workflow.",
                },
                {
                  q: "Can I use Resoomer AI for academic writing?",
                  a: "Yes, Resoomer AI is excellent for academic use, including summarizing papers, simplifying complex texts, and rewriting content plagiarism-free.",
                },
                {
                  q: "How accurate is the content generated by Resoomer AI?",
                  a: "Resoomer AI delivers highly accurate summaries and content adaptations based on AI models trained for clarity, context, and relevance.",
                },
                {
                  q: "Does Resoomer AI support content rewriting?",
                  a: "Yes, besides summarization, Resoomer AI can rephrase and expand your content to match different tones and purposes.",
                },
                {
                  q: "Can I use Resoomer AI without prior writing skills?",
                  a: "Yes, Resoomer AI is beginner-friendly and requires no prior writing or editing skills. The AI simplifies the content creation process for all users.",
                },
                {
                  q: "What types of content can I summarize with Resoomer AI?",
                  a: "You can summarize articles, essays, reports, blog posts, academic papers, and more with Resoomer AI.",
                },
                {
                  q: "Is Resoomer AI suitable for professional writers?",
                  a: "Definitely. Professionals use Resoomer AI to enhance productivity, generate summaries, and reformat content efficiently.",
                },
                {
                  q: "Can I customize the tone of the output in Resoomer AI?",
                  a: "Yes, Resoomer AI allows you to choose a tone such as formal, casual, or professional to match your intended audience.",
                },
                {
                  q: "Does Resoomer AI save or store my content?",
                  a: "Resoomer AI may temporarily process your input for generation purposes, but your content privacy is protected according to the platform’s privacy policy.",
                },
                {
                  q: "Can I collaborate with others on content in Resoomer AI?",
                  a: "Currently, Resoomer AI does not support real-time collaboration, but you can share exported files with others for review or editing.",
                },
                {
                  q: "Is the content from Resoomer AI plagiarism-free?",
                  a: "Yes, Resoomer AI ensures that the output is unique and plagiarism-free, making it suitable for original publications.",
                },
                {
                  q: "Can I expand content instead of summarizing with Resoomer AI?",
                  a: "Yes, Resoomer AI supports both summarization and expansion of content, giving you flexibility depending on your project needs.",
                },
                {
                  q: "How fast is the content generation process in Resoomer AI?",
                  a: "Resoomer AI generates summaries or rephrased content almost instantly, helping you save time on content creation.",
                },
                {
                  q: "Does Resoomer AI require installation?",
                  a: "No installation is required. Resoomer AI is a web-based platform accessible through any modern browser.",
                },
                {
                  q: "What makes Resoomer AI different from other tools?",
                  a: "Resoomer AI stands out with its ability to adapt content based on user input while ensuring originality and copyright freedom.",
                },
                {
                  q: "Does Resoomer AI have a mobile version?",
                  a: "While there is no dedicated app yet, Resoomer AI is mobile-friendly and accessible via your smartphone browser.",
                },
                {
                  q: "Can I use Resoomer AI for business content?",
                  a: "Yes, Resoomer AI is ideal for business applications like summarizing reports, preparing newsletters, or rephrasing marketing materials.",
                },
                {
                  q: "Where can I get support for Resoomer AI?",
                  a: "Resoomer AI offers support through its help center and email, where users can get assistance or report issues.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src={resoomerSS1}
                alt="resoomer"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src={resoomerSS2}
                alt="resoomer"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>Resoomer AI</strong> is the Go-To Tool for
                    Smart, Concise, and Copyright-Free Summarization
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>Resoomer AI</strong> empowers researchers, students,
                    educators, and professionals with an intelligent platform to
                    summarize, refine, and customize content to their exact
                    needs. Whether you're working with academic papers, reports,
                    or lengthy articles, here’s why Resoomer AI stands out:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>AI-Powered Summarization:</strong>{" "}
                      <strong>Resoomer AI</strong> intelligently condenses long
                      texts into concise summaries, tailored to your needs while
                      retaining essential information.
                    </li>
                    <li className="mb-3">
                      <strong>Fast and User-Friendly:</strong> Simplify content
                      quickly using an intuitive interface that requires no
                      technical expertise.
                    </li>
                    <li className="mb-3">
                      <strong>No Copyright Concerns:</strong> All summaries
                      generated by <strong>Resoomer AI</strong> are original and
                      free from copyright infringement, making them ideal for
                      academic or professional use.
                    </li>
                    <li className="mb-3">
                      <strong>Customizable Summaries:</strong> Adjust summary
                      length, structure, or focus points to suit specific use
                      cases like reports, presentations, or reviews.
                    </li>
                    <li className="mb-3">
                      <strong>Web-Based Accessibility:</strong> Use{" "}
                      <strong>Resoomer AI</strong> on any device via the
                      cloud—no software installation needed.
                    </li>
                    <li className="mb-3">
                      <strong>Ideal for Multiple Domains:</strong> Whether
                      you’re a student summarizing a thesis, a marketer refining
                      content, or a journalist condensing articles, Resoomer AI
                      adapts to all scenarios.
                    </li>
                    <li className="mb-3">
                      <strong>Works with External Tools:</strong> After
                      generating your summary, easily copy, download, or export
                      it to your preferred editing environment.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Start Summarizing with <strong>Resoomer AI</strong> —
                      Fast, Smart, and Copyright-Free
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>Resoomer AI</strong> is Revolutionizing Content
              Summarization and Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>Resoomer AI</strong> is changing the landscape of content
              creation by offering powerful AI tools that enable users to
              generate concise, original summaries, and refine content without
              any copyright concerns. Let's explore its key benefits and
              potential drawbacks.
            </p>
            <div className="row justify-content-center gap-2">
              {/* Pros Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">✅ Pros</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>AI-Powered Summarization:</strong> Resoomer AI
                    creates personalized, high-quality summaries instantly,
                    ensuring original content free from copyright issues.
                  </li>
                  <li className="mb-2">
                    <strong>Speedy Content Refinement:</strong> Users can
                    generate well-crafted, concise summaries in just a few
                    minutes, enabling content creators to meet tight deadlines
                    effortlessly.
                  </li>
                  <li className="mb-2">
                    <strong>User-Friendly Interface:</strong> With an intuitive,
                    easy-to-navigate interface, Resoomer AI is suitable for both
                    beginners and seasoned professionals.
                  </li>
                  <li className="mb-2">
                    <strong>Complete Customization:</strong> Users have full
                    control over the final summary by adjusting factors such as
                    tone, style, and structure, tailoring the output to fit
                    their needs.
                  </li>
                  <li className="mb-2">
                    <strong>Original and Copyright-Free Content:</strong>{" "}
                    Resoomer AI guarantees all summaries are free from
                    plagiarism and can be used for commercial purposes without
                    concern.
                  </li>
                </ul>
              </div>

              {/* Cons Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">⚠️ Cons</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Limited Free Version:</strong> The free version of
                    Resoomer AI comes with limited features, with more advanced
                    capabilities available only in the paid plans.
                  </li>
                  <li className="mb-2">
                    <strong>Template-Based Summaries:</strong> While users can
                    customize the output, Resoomer AI relies on pre-defined
                    templates for summarization, which may limit creative
                    freedom for some users.
                  </li>
                  <li className="mb-2">
                    <strong>Basic Writing Style:</strong> For more complex or
                    emotional content, the AI-generated summaries may lack the
                    depth and nuance that a human writer can provide.
                  </li>
                  <li className="mb-2">
                    <strong>Requires Internet Connectivity:</strong> As a
                    cloud-based platform, Resoomer AI requires a stable internet
                    connection, which may not be feasible for users in areas
                    with unreliable connectivity.
                  </li>
                  <li className="mb-2">
                    <strong>Potential Repetitiveness:</strong> Depending on the
                    algorithm, some users may notice slight repetition or lack
                    of uniqueness in the generated summaries across different
                    projects.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover Leading Alternatives to Resoomer AI for Summarization and
              Content Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Resoomer AI</strong> excels at summarizing and
              refining content, several other platforms offer unique
              capabilities for text analysis, summarization, and rewriting,
              helping creators produce concise, high-quality, and original
              content effortlessly.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Resoomer AI</strong>: Specializes in summarizing and
                    refining large bodies of text, ensuring clear and concise
                    content while maintaining the original message. Customize
                    the summaries according to your needs.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeBot</strong>: An AI tool designed to
                    summarize articles, news, or research papers quickly,
                    allowing users to extract key points from lengthy documents
                    without losing important context.
                  </li>
                  <li className="mb-2">
                    <strong>QuillBot</strong>: Offers various AI-powered writing
                    enhancements, including paraphrasing and summarization
                    tools, helping users improve the quality of their writing
                    and create clear, concise content.
                  </li>
                  <li className="mb-2">
                    <strong>SMMRY</strong>: A web-based AI tool that summarizes
                    long texts and articles, ensuring that the main ideas are
                    highlighted in a concise, easy-to-read format.
                  </li>
                  <li className="mb-2">
                    <strong>Text Summarizer</strong>: An online tool that
                    condenses large texts into their most important points,
                    providing an efficient way to summarize content for research
                    or study purposes.
                  </li>
                  <li className="mb-2">
                    <strong>Copy.ai</strong>: An AI-powered writing tool that
                    aids in generating marketing copy, blog posts, and other
                    content, with capabilities for summarizing and refining text
                    for better clarity and engagement.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeThis</strong>: A simple yet effective AI
                    tool for summarizing text, ensuring users can quickly grasp
                    the essence of any content without reading through entire
                    documents.
                  </li>
                  <li className="mb-2">
                    <strong>TLDR This</strong>: Focuses on creating quick,
                    readable summaries from large articles, papers, and
                    documents, ideal for saving time while still capturing the
                    key points.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
        <div className="row align-items-center justify-content-between mb-4">
  {/* Image First on Mobile, Second on Desktop */}
  <div className="col-12 col-md-6 order-1 order-md-2 text-center mb-3 mb-md-0">
    <img
      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
      alt="Resoomer AI"
      style={{ maxWidth: "100%", height: "300px" }}
    />
  </div>

  {/* Text Second on Mobile, First on Desktop */}
  <div className="col-12 col-md-6 order-2 order-md-1" style={{ paddingRight: "30px" }}>
    <p className="text-primary">Write better, faster</p>
    <h1>Resoomer AI:</h1>
    <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
    <p>
      Resoomer is an AI-powered tool designed to automatically summarize long texts into short,
      concise summaries. With the ability to handle complex content like articles, research papers,
      and essays, Resoomer makes it easier for users to digest large amounts of information quickly.
      It is a content summarization solution designed for students, professionals, researchers, and
      content creators who want to save time by streamlining information intake.
    </p>
    <a
      href="https://resoomer.ai/en/"
      rel="noopener noreferrer"
      className="btn btn-primary me-2"
    >
      Explore Tool
    </a>
  </div>
</div>


          <section style={{ backgroundColor: "#1b1f2b", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Elevate Your Content Creation with Resoomer AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                Discover How Resoomer AI Transforms Content Summarization and
                Personalization
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                Resoomer AI helps creators quickly summarize and refine large
                pieces of content, generating concise, original summaries while
                maintaining the integrity of the original message.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Generate Precise Content Summaries
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Resoomer AI quickly generates succinct, relevant summaries
                      for your lengthy documents. Choose your content's focus,
                      and let Resoomer AI produce a refined, concise version in
                      no time.
                    </p>
                    <div className="step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Tailor Summaries to Your Needs
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      With Resoomer AI, you can further personalize your content
                      by adjusting the tone, style, and level of detail in your
                      summaries to perfectly match your requirements.
                    </p>
                    <div className="step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Effortless Integration into Your Workflow
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Resoomer AI seamlessly integrates your summaries into
                      blogs, research papers, articles, and more, making it easy
                      to share concise information without the risk of copyright
                      issues.
                    </p>
                    <div className="step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

         
        </div>
      </div>
    </>
  );
};

export default Resoomer;
