import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const Smmry = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="SMMRY AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Enhance Your Efficiency with SMMRY AI
                </p>
                <h3>
                  Customizable, Copyright-Free Summaries Generated Instantly
                </h3>
              </div>
              {[
                {
                  icon: "⚡",
                  title: "Instant Summarization",
                  desc: "SMMRY AI quickly condenses long texts into concise, easy-to-read summaries, saving you time and effort.",
                },
                {
                  icon: "🔧",
                  title: "Customizable Output",
                  desc: "Control the length, focus, and structure of your summaries to meet your needs, whether for research, business, or personal use.",
                },
                {
                  icon: "🌍",
                  title: "Multi-Language Support",
                  desc: "SMMRY AI supports multiple languages, making it perfect for users around the world.",
                },
                {
                  icon: "📜",
                  title: "Plagiarism-Free Summaries",
                  desc: "Content generated by SMMRY AI is original, ensuring it's safe to use for professional, academic, and commercial purposes.",
                },
                {
                  icon: "📝",
                  title: "Simplified Summarization",
                  desc: "With an easy-to-use interface, SMMRY AI makes summarizing content a straightforward task with no complicated steps.",
                },
                {
                  icon: "🔍",
                  title: "Accurate Extractive Summarization",
                  desc: "SMMRY AI uses a precise algorithm to extract the most relevant sentences from your text to create an accurate summary.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is SMMRY AI?",
                  a: "SMMRY AI is a free, web-based summarization tool that allows users to condense long texts into concise summaries quickly, with full control over output and no copyright concerns.",
                },
                {
                  q: "How does SMMRY AI work?",
                  a: "SMMRY AI extracts key sentences from the input text using a simple algorithm, prioritizing relevance and clarity while removing unnecessary content.",
                },
                {
                  q: "Can SMMRY AI modify content according to my needs?",
                  a: "Yes, SMMRY AI offers options like sentence count, keyword emphasis, and formatting tweaks to help users adjust the summary to their preference.",
                },
                {
                  q: "Is SMMRY AI content copyright-free?",
                  a: "Yes, SMMRY AI provides summaries free of copyright, giving you full freedom to reuse or modify the output.",
                },
                {
                  q: "Can SMMRY AI summarize long documents?",
                  a: "Yes, SMMRY AI can efficiently summarize long documents such as articles, research papers, and essays into shorter formats.",
                },
                {
                  q: "Does SMMRY AI support multiple languages?",
                  a: "SMMRY AI primarily supports English but can work with other languages if the sentence structure is simple.",
                },
                {
                  q: "Is SMMRY AI free to use?",
                  a: "Yes, SMMRY AI is completely free to use with no account or subscription required.",
                },
                {
                  q: "Can I export the content generated by SMMRY AI?",
                  a: "While there are no direct export buttons, you can easily copy and paste the summary into your preferred tool for saving.",
                },
                {
                  q: "Can I use SMMRY AI for academic writing?",
                  a: "Yes, it’s suitable for summarizing academic texts, but manual review is recommended for precision in academic settings.",
                },
                {
                  q: "How accurate is the content generated by SMMRY AI?",
                  a: "SMMRY AI offers a fairly accurate extractive summary based on keywords and relevance but does not use deep contextual AI.",
                },
                {
                  q: "Does SMMRY AI support content rewriting?",
                  a: "No, SMMRY AI is a summarization-only tool and does not support rewriting or paraphrasing features.",
                },
                {
                  q: "Can I use SMMRY AI without prior writing skills?",
                  a: "Yes, it’s designed for simplicity—just paste your text and get a summary in seconds.",
                },
                {
                  q: "What types of content can I summarize with SMMRY AI?",
                  a: "You can summarize blog posts, articles, essays, transcripts, and any other plain text with SMMRY AI.",
                },
                {
                  q: "Is SMMRY AI suitable for professional writers?",
                  a: "Yes, professionals use it for quick previews or to distill content before further writing or editing.",
                },
                {
                  q: "Can I customize the tone of the output in SMMRY AI?",
                  a: "No, SMMRY AI does not offer tone customization—it generates extractive summaries based on original wording.",
                },
                {
                  q: "Does SMMRY AI save or store my content?",
                  a: "No, SMMRY AI does not store user content. Summaries are generated on the fly and not retained.",
                },
                {
                  q: "Can I collaborate with others on content in SMMRY AI?",
                  a: "No collaboration tools are provided, but you can share the summarized content manually.",
                },
                {
                  q: "Is the content from SMMRY AI plagiarism-free?",
                  a: "Yes, summaries are derived from your own input, so there is no issue of plagiarism.",
                },
                {
                  q: "Can I expand content instead of summarizing with SMMRY AI?",
                  a: "No, SMMRY AI only shortens content—it does not support content expansion.",
                },
                {
                  q: "How fast is the content generation process in SMMRY AI?",
                  a: "The summary is generated almost instantly after you paste your content and click summarize.",
                },
                {
                  q: "Does SMMRY AI require installation?",
                  a: "No installation is needed. SMMRY AI is accessible via any web browser.",
                },
                {
                  q: "What makes SMMRY AI different from other tools?",
                  a: "Its simplicity, speed, and no-login-required design make it a go-to for users who want fast results without complication.",
                },
                {
                  q: "Does SMMRY AI have a mobile version?",
                  a: "There’s no mobile app, but the website is mobile-friendly and works well on phones and tablets.",
                },
                {
                  q: "Can I use SMMRY AI for business content?",
                  a: "Yes, it's helpful for summarizing reports, briefings, and articles quickly for business purposes.",
                },
                {
                  q: "Where can I get support for SMMRY AI?",
                  a: "Support is minimal, but basic contact info is available on their website for inquiries.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src="https://www.testingcatalog.com/content/images/size/w2000/2024/06/screenshot-app.runwayml.com-2024.06.24-00_36_32--1-.png"
                alt=""
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src="https://www.techspot.com/articles-info/2720/images/2023-08-17-image.jpg"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use - SMMRY":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>SMMRY AI</strong> is Perfect for Quick,
                    Copyright-Free Summarization on the Go
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>SMMRY AI</strong> provides a clean and fast way to
                    generate summaries from long texts with no copyright issues.
                    Ideal for students, researchers, and content curators who
                    value speed, simplicity, and control, here’s why people rely
                    on it:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Effortless Customization:</strong> Users can
                      adjust summary length and keyword focus, getting tailored
                      results without advanced AI complexity.
                    </li>
                    <li className="mb-3">
                      <strong>Fast Summarization:</strong> Instantly condenses
                      long articles into manageable summaries with just a single
                      click.
                    </li>
                    <li className="mb-3">
                      <strong>No Copyright Restrictions:</strong> Content
                      created with <strong>SMMRY AI</strong> is fully editable,
                      shareable, and safe for both academic and commercial use.
                    </li>
                    <li className="mb-3">
                      <strong>Zero Login or Sign-Up:</strong> You can start
                      summarizing immediately—no accounts, no subscriptions,
                      just paste and go.
                    </li>
                    <li className="mb-3">
                      <strong>Simple Web Interface:</strong> Minimal design
                      makes it beginner-friendly and distraction-free.
                    </li>
                    <li className="mb-3">
                      <strong>Free and Accessible:</strong> 100% free to use
                      with no hidden features—ideal for quick research,
                      summaries, and casual reading.
                    </li>
                    <li className="mb-3">
                      <strong>Lightweight Tool:</strong> Perfect for
                      low-bandwidth environments or older devices due to its
                      minimal resource consumption.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Start Summarizing with <strong>SMMRY AI</strong> — Simple,
                      Fast, and Copyright-Free
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons - SMMRY":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>SMMRY AI</strong> is a Simple Yet Powerful
              Summarization Tool
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>SMMRY AI</strong> offers a no-frills, efficient way to
              condense long texts, with user control over summarization length
              and formatting. It’s ideal for those who want fast, copyright-free
              results without unnecessary complexity.
            </p>
            <div className="row justify-content-center gap-2">
              {/* Pros Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">✅ Pros</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Copyright-Free Summaries:</strong> SMMRY AI produces
                    summaries that are free to use and modify, with no copyright
                    restrictions—ideal for educational and commercial reuse.
                  </li>
                  <li className="mb-2">
                    <strong>Customizable Output:</strong> Users can control the
                    summary length and focus, tailoring the content to their
                    needs without complex settings.
                  </li>
                  <li className="mb-2">
                    <strong>Minimalist & Fast:</strong> The platform is
                    extremely lightweight and efficient, offering instant
                    results with minimal input.
                  </li>
                  <li className="mb-2">
                    <strong>No Sign-Up Required:</strong> Completely web-based
                    and free to use—no registration or login needed.
                  </li>
                  <li className="mb-2">
                    <strong>Simple Interface:</strong> Easy for all users, from
                    students to researchers, to get summaries without a learning
                    curve.
                  </li>
                </ul>
              </div>

              {/* Cons Column */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">⚠️ Cons</h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>No Advanced AI Features:</strong> Unlike other
                    modern tools, SMMRY AI lacks features like tone adjustment,
                    rephrasing, or deep refinement.
                  </li>
                  <li className="mb-2">
                    <strong>Limited Input Options:</strong> Only plain text or
                    URLs can be summarized—no support for PDFs or other document
                    formats.
                  </li>
                  <li className="mb-2">
                    <strong>No Personalization:</strong> Does not offer
                    learning-based customization or memory of user preferences.
                  </li>
                  <li className="mb-2">
                    <strong>Outdated UI:</strong> The interface is basic and may
                    feel outdated to users looking for a modern tool.
                  </li>
                  <li className="mb-2">
                    <strong>No Collaboration Tools:</strong> Lacks export,
                    sharing, or integration features that professionals or teams
                    may require.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover Leading Alternatives to Resoomer AI for Summarization and
              Content Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Resoomer AI</strong> excels at summarizing and
              refining content, several other platforms offer unique
              capabilities for text analysis, summarization, and rewriting,
              helping creators produce concise, high-quality, and original
              content effortlessly.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #7b68ee",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#1e1e1e",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Resoomer AI</strong>: Specializes in summarizing and
                    refining large bodies of text, ensuring clear and concise
                    content while maintaining the original message. Customize
                    the summaries according to your needs.
                  </li>
                  <li className="mb-2">
                    <strong>SMMRY AI</strong>: Allows users to generate
                    copyright-free summaries with control over the content’s
                    length and focus. SMMRY AI adapts to your preferences,
                    offering flexibility without compromising originality or
                    ownership.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeBot</strong>: An AI tool designed to
                    summarize articles, news, or research papers quickly,
                    allowing users to extract key points from lengthy documents
                    without losing important context.
                  </li>
                  <li className="mb-2">
                    <strong>QuillBot</strong>: Offers various AI-powered writing
                    enhancements, including paraphrasing and summarization
                    tools, helping users improve the quality of their writing
                    and create clear, concise content.
                  </li>
                  <li className="mb-2">
                    <strong>Text Summarizer</strong>: An online tool that
                    condenses large texts into their most important points,
                    providing an efficient way to summarize content for research
                    or study purposes.
                  </li>
                  <li className="mb-2">
                    <strong>Copy.ai</strong>: An AI-powered writing tool that
                    aids in generating marketing copy, blog posts, and other
                    content, with capabilities for summarizing and refining text
                    for better clarity and engagement.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizeThis</strong>: A simple yet effective AI
                    tool for summarizing text, ensuring users can quickly grasp
                    the essence of any content without reading through entire
                    documents.
                  </li>
                  <li className="mb-2">
                    <strong>TLDR This</strong>: Focuses on creating quick,
                    readable summaries from large articles, papers, and
                    documents, ideal for saving time while still capturing the
                    key points.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
          <div className=" row d-flex align-items-center justify-content-between mb-1">
            {/* Left side (Text Section) */}
            <div
              style={{ flex: 1, paddingRight: "30px" }}
              className="col-6 col-md-12 "
            >
              <p className="text-primary">Write better, faster</p>
              <h1>SMMRY AI:</h1>
              <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
              <p>
                SMMRY AI tool is an advanced AI summarization platform that
                leverages artificial intelligence to provide users with AI text
                summarizer capabilities. Whether you need to summarize text
                online, summarize documents fast, or condense long pieces of
                content, SMMRY helps streamline the process by reducing lengthy
                materials into concise, easy-to-read summaries.
              </p>

              <div className="mb-3">
                <span className="badge bg-primary me-2">Image Generation</span>
                <span className="badge bg-success me-2">Creative</span>
                <span className="badge bg-warning text-dark">Paid</span>
              </div>
            </div>

            {/* Right side (Image Section) */}
            <div
              style={{
                flex: 1,
                textAlign: "center",
                Width: "100%",
                height: "250px",
              }}
              className="col-6 col-md-12 mb-5  "
            >
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
                style={{ MaxWidth: "100%", height: "300px" }}
              />
            </div>
          </div>

          <section style={{ backgroundColor: "#1b1f2b", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Streamline Your Content Summarization with SMMRY AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                See How SMMRY AI Delivers Instant, Custom, and Copyright-Free
                Summaries
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                SMMRY AI enables users to distill lengthy articles, essays, or
                reports into clear and concise summaries that retain the
                original meaning—fully customizable and copyright-free.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Instantly Summarize Complex Content
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      SMMRY AI scans your documents and creates a short, clear
                      summary within seconds, removing fluff and retaining only
                      essential points.
                    </p>
                    <div className="step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Customize Length and Focus
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Choose the number of key points, set your preferred tone,
                      or prioritize topics—SMMRY AI adapts to your summarization
                      needs.
                    </p>
                    <div className="step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#1034a6",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #7b61ff;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Use Anywhere, Without Copyright Concerns
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Whether it’s for blogs, academic reports, or social media
                      content, SMMRY AI provides copyright-free, shareable
                      summaries ready to use instantly.
                    </p>
                    <div className="step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          <div className="bg-primary text-center text-light rounded-4 p-5 mt-5">
            <h4 className="mb-3">Ready to get started with Smmry?</h4>
            <p className="mb-4">
              Join thousands of professionals already boosting their
              productivity!
            </p>
            <div>
              <button className="btn btn-light me-3">Try Now for Free</button>
              <button className="btn btn-outline-light">Schedule a Demo</button>
            </div>
            <small className="d-block mt-2">
              No credit card required. 14-day free trial available.
            </small>
          </div>
        </div>
      </div>
    </>
  );
};

export default Smmry;
