import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const Coggle = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="Coggle AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Enhance Your Content with Precision and Flexibility Using
                  Coggle AI
                </p>
                <h3>Smart, Seamless Content Enhancement for Every Purpose</h3>
              </div>
              {[
                {
                  icon: "🔍",
                  title: "Advanced Content Clarity",
                  desc: "Coggle AI optimizes the clarity and readability of your content, ensuring every idea is expressed succinctly and effectively.",
                },
                {
                  icon: "🖌️",
                  title: "Flexible Writing Styles",
                  desc: "From formal to casual, or even creative, Coggle AI adapts your writing style to suit any audience or situation.",
                },
                {
                  icon: "🌐",
                  title: "Multilingual and Multi-format Support",
                  desc: "Supports a wide range of file formats (DOCX, PDF, TXT) and can refine content in multiple languages, making it versatile for global use.",
                },
                {
                  icon: "✍️",
                  title: "100% Unique and Original Content",
                  desc: "Every piece of content generated by Coggle AI is plagiarism-free, ensuring authenticity and originality in all your materials.",
                },
                {
                  icon: "🎯",
                  title: "Tailored Contextual Refinement",
                  desc: "Coggle AI adjusts content based on its context, enhancing its relevance and making it more engaging for your audience.",
                },
                {
                  icon: "📚",
                  title: "Suitable for Various Content Types",
                  desc: "Perfect for editing reports, articles, academic papers, and creative writing, Coggle AI delivers polished content for all uses.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is Coggle AI?",
                  a: "Coggle AI is a cutting-edge tool designed to help users improve their content by enhancing readability, structure, and clarity, whether for professional, academic, or personal writing projects.",
                },
                {
                  q: "How does Coggle AI work?",
                  a: "Coggle AI leverages advanced machine learning algorithms to analyze and refine your content, adjusting tone, flow, and coherence while preserving the original message and context.",
                },
                {
                  q: "Is the content from Coggle AI free of copyright issues?",
                  a: "Yes, Coggle AI guarantees that all content generated is unique and free from copyright concerns, ensuring your material is safe for use across various platforms.",
                },
                {
                  q: "Can I customize how Coggle AI edits my content?",
                  a: "Absolutely! Coggle AI offers customization options to adjust tone, style, and complexity, allowing you to fine-tune content for reports, emails, creative writing, and more.",
                },
                {
                  q: "Can Coggle AI handle large documents?",
                  a: "Yes, Coggle AI is optimized to efficiently process large documents, making it ideal for handling lengthy reports, research papers, and complex content.",
                },
                {
                  q: "What file formats are supported by Coggle AI?",
                  a: "Coggle AI supports a wide range of file formats, including DOCX, PDF, TXT, and more, ensuring seamless editing and enhancement across different content types.",
                },
                {
                  q: "Is Coggle AI free to use?",
                  a: "Coggle AI offers both a free and a premium version. The free version provides essential features, while the premium version unlocks advanced customization options and extra functionality.",
                },
                {
                  q: "Can I export my content after editing it?",
                  a: "Yes, once your content is refined, you can export it in various formats, depending on your subscription level.",
                },
                {
                  q: "Is Coggle AI suitable for students?",
                  a: "Definitely! Students can use Coggle AI to improve their essays, summarize study materials, and enhance academic writing, making it a valuable tool for learning.",
                },
                {
                  q: "Does Coggle AI ensure plagiarism-free output?",
                  a: "Yes, every piece of content generated by Coggle AI is unique and free from plagiarism, ensuring authenticity and originality.",
                },
                {
                  q: "Is Coggle AI user-friendly?",
                  a: "Yes, Coggle AI features an intuitive, user-friendly interface, making it accessible to users with varying levels of experience and expertise.",
                },
                {
                  q: "Can I set a specific tone for my content?",
                  a: "Absolutely! Coggle AI allows you to choose from various tones, including formal, casual, professional, or conversational, ensuring the style matches the purpose of your content.",
                },
                {
                  q: "Can businesses use Coggle AI?",
                  a: "Yes, Coggle AI is an excellent tool for businesses to generate high-quality reports, emails, marketing materials, proposals, and more, helping streamline content creation.",
                },
                {
                  q: "Does Coggle AI store my text or files?",
                  a: "No, Coggle AI does not store any user content after processing. Your data is handled securely and is not retained, ensuring your privacy.",
                },
                {
                  q: "Can I access Coggle AI from my mobile device?",
                  a: "Yes, Coggle AI is fully responsive and can be accessed from any device with an internet connection, offering flexibility for users on the go.",
                },
                {
                  q: "Is technical knowledge required to use Coggle AI?",
                  a: "No, Coggle AI is designed to be easy to use, so no technical expertise is needed. Anyone can start refining content right away.",
                },
                {
                  q: "Does Coggle AI only paraphrase content?",
                  a: "No, Coggle AI does more than just paraphrase. It improves the structure, coherence, and clarity of content, making it more effective and readable while retaining its original meaning.",
                },
                {
                  q: "How quickly does Coggle AI rewrite content?",
                  a: "Coggle AI operates at lightning speed, delivering quick, efficient content refinement in just seconds.",
                },
                {
                  q: "Do I need to install anything to use Coggle AI?",
                  a: "No installation is required! Coggle AI is a cloud-based platform that you can access through any web browser, ensuring a smooth, hassle-free experience.",
                },
                {
                  q: "Where can I get support for Coggle AI?",
                  a: "You can reach Coggle AI support through the help center or contact form available on the website, where our team is ready to assist you.",
                },
                {
                  q: "Can Coggle AI be used for creative writing?",
                  a: "Yes, Coggle AI is great for creative writing. Whether you're brainstorming ideas, drafting stories, or refining articles, it helps keep your creative direction intact.",
                },
                {
                  q: "Can I use Coggle AI to summarize long texts?",
                  a: "Yes, Coggle AI can summarize lengthy content into concise, easy-to-read summaries while keeping key information intact.",
                },
                {
                  q: "Is Coggle AI useful for content marketers?",
                  a: "Definitely! Content marketers can use Coggle AI to create compelling copy, social media posts, ads, and more, ensuring content resonates with the target audience.",
                },
                {
                  q: "How secure is Coggle AI?",
                  a: "Coggle AI prioritizes security, implementing strong data protection measures to ensure your content is processed safely and securely.",
                },
                {
                  q: "Can Coggle AI handle multilingual content?",
                  a: "Yes, Coggle AI can process content in multiple languages, making it an ideal solution for international projects and audiences.",
                },
                {
                  q: "Does Coggle AI offer any integrations with other tools?",
                  a: "Yes, Coggle AI integrates with popular content management systems and productivity tools, improving workflow efficiency and enhancing productivity.",
                },
                {
                  q: "Is Coggle AI suitable for eCommerce content?",
                  a: "Yes, Coggle AI is perfect for refining eCommerce content, including product descriptions, customer reviews, and promotional materials.",
                },
                {
                  q: "Can Coggle AI help with SEO content?",
                  a: "Yes, Coggle AI can optimize your content for SEO, helping it rank higher on search engines while engaging your target audience effectively.",
                },
                {
                  q: "Can I adjust the complexity of my content with Coggle AI?",
                  a: "Yes, Coggle AI allows you to adjust the complexity of your content, whether you want to simplify it for a broader audience or make it more technical for experts.",
                },
                {
                  q: "Can I use Coggle AI for content rephrasing in legal documents?",
                  a: "While Coggle AI can assist with general content editing, we recommend consulting legal professionals for documents that require precise legal language.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src="https://www.testingcatalog.com/content/images/size/w2000/2024/06/screenshot-app.runwayml.com-2024.06.24-00_36_32--1-.png"
                alt=""
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src="https://www.techspot.com/articles-info/2720/images/2023-08-17-image.jpg"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>Coggle AI</strong> is the Ultimate Tool for
                    Streamlined Content Refinement and Clarity
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>Coggle AI</strong> revolutionizes the content
                    creation process by simplifying intricate texts and
                    enhancing their clarity. Whether you’re crafting a report,
                    writing an article, or fine-tuning a proposal, here’s why{" "}
                    <strong>Coggle AI</strong> is the perfect solution for
                    content enhancement:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Effortless Text Simplification:</strong> Easily
                      transforms complex content into clear, concise, and
                      engaging material, making it accessible to any audience.
                    </li>
                    <li className="mb-3">
                      <strong>Plagiarism-Free and Unique Output:</strong>{" "}
                      Generates fresh, original content, ensuring that your
                      material is both creative and free from plagiarism.
                    </li>
                    <li className="mb-3">
                      <strong>Adaptable Writing Styles:</strong> Allows you to
                      modify the tone and style to match your needs—whether you
                      require formal, friendly, technical, or casual writing.
                    </li>
                    <li className="mb-3">
                      <strong>Fast and Reliable Results:</strong> Delivers quick
                      and high-quality content adjustments, perfect for meeting
                      tight deadlines and producing polished work on demand.
                    </li>
                    <li className="mb-3">
                      <strong>Easy-to-Use Interface:</strong> With its
                      user-friendly design, <strong>Coggle AI</strong>{" "}
                      simplifies content enhancement, making it easy for anyone,
                      regardless of experience, to refine their work.
                    </li>
                    <li className="mb-3">
                      <strong>Versatile for All Content Types:</strong> From
                      business emails to academic papers,{" "}
                      <strong>Coggle AI</strong> is ideal for a wide range of
                      content formats, offering flexibility for different use
                      cases.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Experience <strong>Coggle AI</strong> — Elevate Your
                      Content with Precision and Ease
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>Coggle AI</strong> is a Cutting-Edge Tool for Content
              Simplification
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>Coggle AI</strong> transforms complex, technical, and
              jargon-heavy content into clear, engaging, and easily digestible
              material, helping users communicate more effectively.
            </p>

            {/* Coggle AI Section */}
            <div className="row justify-content-center gap-2 mb-5">
              {/* Coggle AI Pros */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#2c353f",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">
                  ✅ Coggle AI - Pros
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Content Simplification:</strong> Streamlines
                    complicated information, making it more accessible to a wide
                    range of readers while keeping essential details intact.
                  </li>
                  <li className="mb-2">
                    <strong>Customizable Tone and Style:</strong> Offers
                    flexibility to adjust tone and style according to the
                    content type, from professional reports to casual blog
                    posts.
                  </li>
                  <li className="mb-2">
                    <strong>Efficient Summarization:</strong> Quickly summarizes
                    long texts into concise and easy-to-understand versions
                    without losing the key ideas.
                  </li>
                  <li className="mb-2">
                    <strong>Versatile Content Formats:</strong> Supports
                    multiple content types, such as articles, research papers,
                    emails, and more, making it a versatile tool for any writer.
                  </li>
                  <li className="mb-2">
                    <strong>Context-Aware Adjustments:</strong> Adapts to the
                    context of the content, ensuring that the simplified text
                    maintains coherence and relevance to the original message.
                  </li>
                </ul>
              </div>

              {/* Coggle AI Cons */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#2c353f",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">
                  ⚠️ Coggle AI - Cons
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Dependency on Internet:</strong> Since it is an
                    online tool, users need a stable internet connection, which
                    can be a limitation in offline or low-connectivity
                    environments.
                  </li>
                  <li className="mb-2">
                    <strong>Limited Creativity Support:</strong> While it excels
                    at simplifying factual and technical content, Coggle AI may
                    not be the best fit for creative or narrative-heavy writing.
                  </li>
                  <li className="mb-2">
                    <strong>Potential for Oversimplification:</strong> In some
                    cases, the tool may oversimplify content, removing crucial
                    information or context that is important for in-depth
                    understanding.
                  </li>
                  <li className="mb-2">
                    <strong>No Citation Generation:</strong> Coggle AI does not
                    automatically generate citations or references, requiring
                    users to handle these elements manually.
                  </li>
                  <li className="mb-2">
                    <strong>Advanced Features Behind Paywall:</strong> Access to
                    premium features, such as batch processing and advanced
                    customization, is restricted to paid plans.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Explore Top Alternatives to Coggle AI for Seamless Content
              Simplification
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Coggle AI</strong> is a powerful tool for
              simplifying and streamlining complex information into clear,
              actionable content, there are other remarkable tools available
              that offer unique features for content transformation,
              paraphrasing, and summarization.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #0062cc",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#2c353f",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Coggle AI</strong>: Specializes in simplifying
                    intricate concepts and ideas, transforming them into
                    structured and easily digestible content without losing
                    meaning.
                  </li>
                  <li className="mb-2">
                    <strong>SimplifyNow</strong>: Focuses on breaking down
                    complex, dense text into more accessible language, making it
                    easier for readers to grasp difficult subjects.
                  </li>
                  <li className="mb-2">
                    <strong>SharpWrite</strong>: Ideal for technical and
                    scientific content, SharpWrite ensures that complex
                    information is communicated in a simplified manner while
                    retaining accuracy.
                  </li>
                  <li className="mb-2">
                    <strong>EasySummarize</strong>: A tool that condenses
                    lengthy documents or articles into shorter, more concise
                    versions while keeping the critical points intact.
                  </li>
                  <li className="mb-2">
                    <strong>FlexiTone</strong>: Allows users to adjust the tone,
                    style, and level of detail in their content, making it ideal
                    for different communication settings, from formal to casual.
                  </li>
                  <li className="mb-2">
                    <strong>BrandVoice</strong>: A marketing-centric tool that
                    tailors content to fit a brand's voice, ensuring consistent
                    messaging and tone across various marketing channels.
                  </li>
                  <li className="mb-2">
                    <strong>ConcisePro</strong>: Designed for reducing content
                    volume, ConcisePro summarizes large documents, retaining
                    only the essential details for quicker understanding.
                  </li>
                  <li className="mb-2">
                    <strong>WriteFlex</strong>: A versatile tool that enables
                    the adjustment of both the complexity and creative style of
                    writing, providing full control over the writing process.
                  </li>
                  <li className="mb-2">
                    <strong>DocClear</strong>: Specialized for simplifying
                    technical or legal documents, DocClear ensures clarity while
                    maintaining the integrity of specialized content.
                  </li>
                  <li className="mb-2">
                    <strong>QuickText</strong>: Known for its rapid content
                    summarization, QuickText extracts key insights from lengthy
                    documents in a flash for quick content digestion.
                  </li>
                  <li className="mb-2">
                    <strong>FlowWriter</strong>: Optimizes content flow and
                    readability, making it an excellent choice for improving
                    business reports, communications, and creative writing
                    projects.
                  </li>
                  <li className="mb-2">
                    <strong>TechEdit</strong>: Aimed at professionals, TechEdit
                    refines highly technical content, making it clearer while
                    preserving all the essential details and technical accuracy.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
          <div className=" row d-flex align-items-center justify-content-between mb-1">
            {/* Left side (Text Section) */}
            <div
              style={{ flex: 1, paddingRight: "30px" }}
              className="col-6 col-md-12 "
            >
              <p className="text-primary">Write better, faster</p>
              <h1>Coggle AI:</h1>
              <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
              <p>
                Coggle AI is an innovative mind mapping and productivity tool
                that uses artificial intelligence to help individuals and teams
                organize their ideas, streamline workflows, and manage tasks
                more efficiently. Coggle’s intuitive platform allows users to
                create visually appealing mind maps, collaborate with team
                members, track progress, and automate task management. Whether
                you are brainstorming, planning a project, or organizing your
                ideas, Coggle AI helps bring clarity and structure to complex
                concepts, making it an essential tool for business planning,
                strategic thinking, content creation, and more.
              </p>

              <div className="mb-3">
                <span className="badge bg-primary me-2">Image Generation</span>
                <span className="badge bg-success me-2">Creative</span>
                <span className="badge bg-warning text-dark">Paid</span>
              </div>
            </div>

            {/* Right side (Image Section) */}
            <div
              style={{
                flex: 1,
                textAlign: "center",
                Width: "100%",
                height: "250px",
              }}
              className="col-6 col-md-12 mb-5  "
            >
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
                style={{ MaxWidth: "100%", height: "300px" }}
              />
            </div>
          </div>

          <section style={{ backgroundColor: "#2b3e55", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Unleash the Power of Simplicity—Transform Complex Ideas with
                Coggle AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                Explore How Coggle AI Simplifies Complex Thoughts into Clear,
                Concise Content
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                Coggle AI simplifies intricate information, breaking it down
                into digestible, clear, and impactful content while ensuring
                originality and precision.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#2c8cd5",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .coggle-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #d1e5f1;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      In-Depth Content Analysis
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Coggle AI thoroughly analyzes your content, breaking down
                      complex language and highlighting the key concepts for
                      clarity and ease of understanding.
                    </p>
                    <div className="coggle-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#2c8cd5",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .coggle-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #d1e5f1;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Personalized Content Customization
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Tailor the tone, language, and structure of your content
                      to fit any audience, from formal to casual, ensuring your
                      message resonates.
                    </p>
                    <div className="coggle-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#2c8cd5",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .coggle-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #d1e5f1;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Ready-to-Use, Unique Content
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Coggle AI ensures that all generated content is 100%
                      original and free from plagiarism, ready for immediate
                      use.
                    </p>
                    <div className="coggle-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          <div className="bg-primary text-center text-light rounded-4 p-5 mt-5">
            <h4 className="mb-3">Ready to get started with Coggle AI?</h4>
            <p className="mb-4">
              Join thousands of professionals already boosting their
              productivity!
            </p>
            <div>
              <button className="btn btn-light me-3">Try Now for Free</button>
              <button className="btn btn-outline-light">Schedule a Demo</button>
            </div>
            <small className="d-block mt-2">
              No credit card required. 14-day free trial available.
            </small>
          </div>
        </div>
      </div>
    </>
  );
};

export default Coggle;
