import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";
import freemindSS1 from '../../../../public/assets/Img/Ai for Mind Mapping/freemindSS1.png';
import freemindSS2 from '../../../../public/assets/Img/Ai for Mind Mapping/freemindSS2.png';


// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const FreeMind = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="FreeMind AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Effortlessly Optimize and Personalize Your Content with
                  FreeMind AI
                </p>
                <h3>
                  Smart, Flexible Content Enhancement for Every Writing Need
                </h3>
              </div>
              {[
                {
                  icon: "🔧",
                  title: "Smart Content Optimization",
                  desc: "FreeMind AI expertly refines your content, improving readability and structure while preserving the original meaning and tone.",
                },
                {
                  icon: "🖋️",
                  title: "Fully Customizable Tone and Style",
                  desc: "Tailor the tone, voice, and complexity of your content for any situation—whether professional, casual, or creative.",
                },
                {
                  icon: "📄",
                  title: "Wide Format and Language Support",
                  desc: "FreeMind AI supports a variety of formats like DOCX, PDF, and TXT, and provides high-quality content refinement in multiple languages.",
                },
                {
                  icon: "💎",
                  title: "Plagiarism-Free, 100% Original Content",
                  desc: "All content generated by FreeMind AI is 100% unique and free from plagiarism, ensuring your work is authentic and reliable.",
                },
                {
                  icon: "🎯",
                  title: "Context-Aware Editing",
                  desc: "FreeMind AI enhances content by adapting to the context, making your writing clearer, more concise, and more engaging while staying true to your message.",
                },
                {
                  icon: "📝",
                  title: "Perfect for All Types of Content",
                  desc: "From business reports to creative writing, FreeMind AI transforms complex text into clear, compelling, and easy-to-understand content.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is FreeMind AI?",
                  a: "FreeMind AI is an advanced platform designed to streamline content enhancement with speed, precision, and creativity, making it perfect for various writing needs including professional, academic, and personal projects.",
                },
                {
                  q: "How does FreeMind AI work?",
                  a: "FreeMind AI uses intelligent algorithms to analyze your content, then refines it by adjusting tone, simplifying complex ideas, and improving structure, ensuring clarity and readability.",
                },
                {
                  q: "Is the content from FreeMind AI free of copyright issues?",
                  a: "Yes, FreeMind AI guarantees that all generated content is 100% original and free from any copyright issues, ensuring it is safe to use for all purposes.",
                },
                {
                  q: "Can I customize how FreeMind AI edits my content?",
                  a: "Yes, you can easily customize the tone, style, and complexity of the content to match your specific requirements, whether for business reports, casual writing, or academic work.",
                },
                {
                  q: "Can FreeMind AI handle large documents?",
                  a: "Absolutely! FreeMind AI is optimized to process large documents quickly and efficiently, making it ideal for detailed reports, research papers, and extensive content.",
                },
                {
                  q: "What file formats are supported by FreeMind AI?",
                  a: "FreeMind AI supports a variety of file formats, including DOCX, PDF, TXT, and more, making it easy to edit and refine your existing content.",
                },
                {
                  q: "Is FreeMind AI free to use?",
                  a: "FreeMind AI offers both a free version with essential features and a premium version that provides advanced customization, enhanced tools, and greater flexibility.",
                },
                {
                  q: "Can I export my content after editing it?",
                  a: "Yes, FreeMind AI allows you to export your edited content in the format of your choice, depending on your subscription plan.",
                },
                {
                  q: "Is FreeMind AI suitable for students?",
                  a: "Yes, students can benefit from FreeMind AI by refining essays, summarizing study materials, and enhancing their academic writing with ease.",
                },
                {
                  q: "Does FreeMind AI ensure plagiarism-free output?",
                  a: "Yes, all content generated by FreeMind AI is guaranteed to be original and free from plagiarism, ensuring its authenticity.",
                },
                {
                  q: "Is FreeMind AI user-friendly?",
                  a: "Yes, FreeMind AI is designed with a simple, intuitive interface that makes it easy to use for individuals of all technical backgrounds.",
                },
                {
                  q: "Can I set a specific tone for my content?",
                  a: "Yes, FreeMind AI allows you to choose from a wide range of tones, such as formal, casual, professional, or conversational, to suit your needs.",
                },
                {
                  q: "Can businesses use FreeMind AI?",
                  a: "Definitely! FreeMind AI is an excellent tool for businesses to generate high-quality reports, marketing content, emails, and proposals quickly and effectively.",
                },
                {
                  q: "Does FreeMind AI store my text or files?",
                  a: "No, FreeMind AI respects your privacy and does not store any content after editing. Your data is processed securely and not retained.",
                },
                {
                  q: "Can I access FreeMind AI from my mobile device?",
                  a: "Yes, FreeMind AI is fully responsive and can be accessed on any mobile device with an internet connection, offering flexibility on the go.",
                },
                {
                  q: "Is technical knowledge required to use FreeMind AI?",
                  a: "No, FreeMind AI is designed to be intuitive and requires no technical expertise, making it accessible to anyone, regardless of their experience.",
                },
                {
                  q: "Does FreeMind AI only paraphrase content?",
                  a: "No, FreeMind AI goes beyond basic paraphrasing. It enhances content by restructuring it for better flow, clarity, and engagement, while maintaining the original meaning.",
                },
                {
                  q: "How quickly does FreeMind AI rewrite content?",
                  a: "FreeMind AI works at lightning speed, delivering refined and polished content in just a few seconds.",
                },
                {
                  q: "Do I need to install anything to use FreeMind AI?",
                  a: "No installation is needed. FreeMind AI is entirely cloud-based and can be accessed through any web browser, offering a seamless user experience.",
                },
                {
                  q: "Where can I get support for FreeMind AI?",
                  a: "You can reach our dedicated support team via the help center or contact form available on the FreeMind AI website for any assistance.",
                },
                {
                  q: "Can FreeMind AI be used for creative writing?",
                  a: "Yes, FreeMind AI is great for creative writing, helping you brainstorm ideas, draft stories, and refine blog posts or articles while staying true to your creative vision.",
                },
                {
                  q: "Can I use FreeMind AI to summarize long texts?",
                  a: "Yes, FreeMind AI can summarize lengthy content by condensing it into concise, easy-to-read summaries while maintaining the key points.",
                },
                {
                  q: "Is FreeMind AI useful for content marketers?",
                  a: "Absolutely! Content marketers can use FreeMind AI to generate engaging copy, social media posts, ads, and more, ensuring their content resonates with the target audience.",
                },
                {
                  q: "How secure is FreeMind AI?",
                  a: "FreeMind AI prioritizes security, ensuring that all content is processed securely with strict data protection protocols in place.",
                },
                {
                  q: "Can FreeMind AI handle multilingual content?",
                  a: "Yes, FreeMind AI can work with content in multiple languages, making it a versatile tool for international projects and multilingual audiences.",
                },
                {
                  q: "Does FreeMind AI offer any integrations with other tools?",
                  a: "Yes, FreeMind AI integrates with popular content management systems and productivity tools, streamlining your workflow and enhancing your productivity.",
                },
                {
                  q: "Is FreeMind AI suitable for eCommerce content?",
                  a: "Yes, FreeMind AI is perfect for generating and refining eCommerce content, such as product descriptions, customer reviews, and promotional material.",
                },
                {
                  q: "Can FreeMind AI help with SEO content?",
                  a: "Yes, FreeMind AI can optimize content for search engines, ensuring that it ranks well and is engaging for your target audience.",
                },
                {
                  q: "Can I adjust the complexity of my content with FreeMind AI?",
                  a: "Yes, FreeMind AI allows you to adjust the complexity of your content, whether you need it simplified for a broad audience or more technical for an expert level.",
                },
                {
                  q: "Can I use FreeMind AI for content rephrasing in legal documents?",
                  a: "While FreeMind AI can assist with general content editing, we recommend seeking professional legal assistance for any legal documents that require precision and accuracy.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img

                src={freemindSS1}

                alt="freemind"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src={freemindSS2}

                alt="freemind"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>FreeMind AI</strong> is the Ultimate Tool for
                    Effortless Content Optimization and Refinement
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>FreeMind AI</strong> revolutionizes content creation
                    by streamlining the refinement process with precision and
                    creativity. Whether you’re improving a report, drafting an
                    email, or enhancing blog content, here’s why FreeMind AI is
                    the go-to solution:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Instant Content Enhancement:</strong> Refining
                      your content quickly without compromising the integrity of
                      your message—giving you polished output in seconds.
                    </li>
                    <li className="mb-3">
                      <strong>100% Original and Unique Outputs:</strong>{" "}
                      Delivers fresh, plagiarism-free content suitable for
                      various uses, from casual blogs to professional reports.
                    </li>
                    <li className="mb-3">
                      <strong>Adjustable Writing Tone:</strong> Customizes the
                      tone to your needs—whether you need a formal, casual,
                      persuasive, or technical style, FreeMind AI adapts
                      accordingly.
                    </li>
                    <li className="mb-3">
                      <strong>Fast and Reliable Results:</strong> Provides quick
                      refinements without losing quality, helping you meet
                      deadlines and produce top-notch content every time.
                    </li>
                    <li className="mb-3">
                      <strong>User-Friendly Interface:</strong> With its
                      intuitive and easy-to-navigate design, FreeMind AI makes
                      content refinement accessible for everyone—whether you’re
                      an expert or a beginner.
                    </li>
                    <li className="mb-3">
                      <strong>Highly Versatile:</strong> Perfect for a broad
                      range of content types, from business emails to academic
                      papers, marketing copy to creative writing.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Try <strong>FreeMind AI</strong> — Unlock the Power of
                      Effortless and Creative Content Refinement
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>FreeMind AI</strong> is an Exceptional and
              Cutting-Edge Tool for Content Refinement
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>FreeMind AI</strong> transforms the way you create and
              refine content, elevating writing quality and clarity while
              ensuring originality with minimal effort.
            </p>

            {/* FreeMind AI Section */}
            <div className="row justify-content-center gap-2 mb-5">
              {/* FreeMind AI Pros */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">
                  ✅ FreeMind AI - Pros
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Adaptable Writing Style:</strong> Offers flexibility
                    to adjust writing tone and style based on the context,
                    ranging from professional to casual or even technical.
                  </li>
                  <li className="mb-2">
                    <strong>Top-Quality, Unique Outputs:</strong> Ensures that
                    content remains original, avoiding plagiarism while
                    maintaining a high standard of clarity and structure.
                  </li>
                  <li className="mb-2">
                    <strong>Fast Content Optimization:</strong> Quickly
                    processes text and enhances its structure, making it more
                    coherent and easier to read in real time.
                  </li>
                  <li className="mb-2">
                    <strong>Contextual Understanding:</strong> Retains the
                    original meaning of the content while optimizing its
                    presentation for better readability and engagement.
                  </li>
                  <li className="mb-2">
                    <strong>Versatility Across Formats:</strong> Whether you're
                    working on blogs, academic papers, business reports, or
                    emails, FreeMind AI is designed to cater to diverse content
                    needs.
                  </li>
                </ul>
              </div>

              {/* FreeMind AI Cons */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">
                  ⚠️ FreeMind AI - Cons
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Requires Internet Access:</strong> As an online
                    tool, FreeMind AI depends on a stable internet connection,
                    which may limit accessibility in some situations.
                  </li>
                  <li className="mb-2">
                    <strong>Less Effective for Creative Writing:</strong> While
                    excellent for academic, technical, and business content,
                    FreeMind AI may not be the best fit for writing fiction or
                    narrative-driven content.
                  </li>
                  <li className="mb-2">
                    <strong>Risk of Over-Simplification:</strong> For some
                    complex subjects, FreeMind AI might overly simplify content,
                    missing out on some intricate details that could be crucial
                    to the original material.
                  </li>
                  <li className="mb-2">
                    <strong>Lack of Citation Features:</strong> Unlike other
                    writing tools, FreeMind AI does not generate citations or
                    references, so users need to manually handle citations.
                  </li>
                  <li className="mb-2">
                    <strong>
                      Premium Access Needed for Advanced Features:
                    </strong>{" "}
                    Some of the more advanced capabilities, such as batch
                    processing or custom tone settings, are available only with
                    the paid version of FreeMind AI.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover the Best Alternatives to FreeMind AI for Seamless Content
              Transformation
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>FreeMind AI</strong> is known for its ability to
              transform complex content into clear, engaging material while
              preserving core ideas, there are several other tools available,
              each offering unique features for content simplification,
              paraphrasing, and summarization.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #007bff",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>FreeMind AI</strong>: Specializes in breaking down
                    intricate ideas and rewriting them in a way that retains the
                    core message, making content more engaging, structured, and
                    clear for all audiences.
                  </li>
                  <li className="mb-2">
                    <strong>ClearText</strong>: Known for its simple and direct
                    approach, ClearText transforms dense, jargon-heavy content
                    into straightforward language that anyone can understand.
                  </li>
                  <li className="mb-2">
                    <strong>ScholarlyWrite</strong>: Tailored for academic
                    purposes, ScholarlyWrite refines research papers and
                    scholarly articles, making them easier to read while
                    preserving their technical depth.
                  </li>
                  <li className="mb-2">
                    <strong>SummarizePro</strong>: Focuses on distilling lengthy
                    articles or research papers into concise, digestible
                    summaries, allowing users to grasp the key points without
                    having to read the entire text.
                  </li>
                  <li className="mb-2">
                    <strong>TextRefine</strong>: Offers the flexibility to
                    adjust the tone and style of your writing, whether it’s
                    formal, informal, or technical, to fit your specific
                    audience.
                  </li>
                  <li className="mb-2">
                    <strong>BrandVoice</strong>: Perfect for marketers,
                    BrandVoice customizes content to align with specific brand
                    identities and communication guidelines, making sure it
                    resonates with the intended audience.
                  </li>
                  <li className="mb-2">
                    <strong>CondenseIt</strong>: This tool helps reduce lengthy
                    documents or reports into shorter versions without losing
                    critical information, perfect for users who need a more
                    concise output.
                  </li>
                  <li className="mb-2">
                    <strong>WriteFlex</strong>: A versatile tool that allows
                    full customization of writing complexity, style, and
                    creativity, providing you with full control over the tone
                    and structure of the content.
                  </li>
                  <li className="mb-2">
                    <strong>DocEase</strong>: Specializes in simplifying legal,
                    scientific, and technical documents, ensuring they remain
                    accurate while making them easy to read for a wider
                    audience.
                  </li>
                  <li className="mb-2">
                    <strong>SwiftSummary</strong>: Designed for quick and
                    efficient summarization, SwiftSummary condenses large texts
                    into bite-sized, readable formats, focusing on the essential
                    ideas.
                  </li>
                  <li className="mb-2">
                    <strong>FlowWriter</strong>: This tool enhances content flow
                    and readability, perfect for improving reports, business
                    communications, and creative writing projects.
                  </li>
                  <li className="mb-2">
                    <strong>ProEditor</strong>: Aimed at professionals,
                    ProEditor helps refine complex technical content, ensuring
                    clarity, precision, and conciseness while maintaining
                    technical accuracy.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
         <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
       <div className="row d-flex align-items-center justify-content-between mb-1 flex-column flex-md-row">
  {/* Image First on Mobile, Right Side on Desktop */}
  <div className="col-12 col-md-6 order-1 order-md-2 mb-3 mb-md-0 text-center">
    <img
      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
      alt="FreeMind AI"
      style={{ width: "100%", height: "300px", objectFit: "cover" }}
    />
  </div>

  {/* Text Second on Mobile, Left Side on Desktop */}
  <div className="col-12 col-md-6 order-2 order-md-1" style={{ paddingRight: "30px" }}>
    <p className="text-primary">Write better, faster</p>
    <h1>FreeMind AI:</h1>
    <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
    <p>
      FreeMind AI is an advanced mind mapping and productivity tool
      designed to help users visually organize ideas, manage tasks,
      and plan projects. By integrating artificial intelligence,
      FreeMind AI streamlines task prioritization, enhances team
      collaboration, and boosts personal productivity. It provides an
      intuitive platform that caters to creative professionals,
      business strategists, and project managers, enabling them to
      create mind maps, brainstorm ideas, plan strategically, and
      track tasks seamlessly. Whether you're looking to visualize
      complex concepts, streamline workflows, or collaborate with your
      team, FreeMind AI is a versatile solution to enhance both
      individual and team productivity.
    </p>
    <a
      href="https://freemindgroup.com/"
      rel="noopener noreferrer"
      className="btn btn-primary me-2"
    >
      Explore Tool
    </a>
  </div>
</div>


          <section style={{ backgroundColor: "#2e3b4e", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Unlock the Power of Precision—Transform Your Ideas with FreeMind
                AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                Discover How FreeMind AI Turns Complex Concepts into Clear,
                Engaging Content
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                FreeMind AI simplifies intricate, technical language into clear
                and impactful content, while ensuring your core message remains
                intact and all output is 100% original and copyright-free.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .freemind-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      In-Depth Content Analysis
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      FreeMind AI thoroughly examines your content, extracting
                      key ideas and nuances to ensure a precise transformation
                      that aligns with your objectives.
                    </p>
                    <div className="freemind-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .freemind-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Tailored Content Personalization
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Customize the tone, style, and complexity of your content
                      to match the needs of your audience—be it for
                      professional, casual, or specialized communication.
                    </p>
                    <div className="freemind-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .freemind-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      100% Original, Ready-to-Publish Content
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Every piece of content generated by FreeMind AI is 100%
                      original, ensuring no plagiarism and making it ready for
                      immediate use in any format.
                    </p>
                    <div className="freemind-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

         
        </div>
      </div>
    </>
  );
};

export default FreeMind;
