import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";
import mindnodeSS1 from '../../../../public/assets/Img/Ai for Mind Mapping/mindnodeSS1.png';
import mindnodeSS2 from '../../../../public/assets/Img/Ai for Mind Mapping/mindnodeSS2.png';
import mindnodeImg from '../../../../public/assets/Img/Ai for Mind Mapping/5.png'

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const MindNode = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="MindNode AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Seamlessly Enhance and Personalize Your Text with MindNode AI
                </p>
                <h3>
                  Advanced, Adaptive Content Refinement Engine for Every Writing
                  Need
                </h3>
              </div>
              {[
                {
                  icon: "🔄",
                  title: "Smart Content Rewriting",
                  desc: "MindNode AI effortlessly refines your text, ensuring clarity, structure, and relevance, all while maintaining the original message intact.",
                },
                {
                  icon: "🎨",
                  title: "Flexible Tone Customization",
                  desc: "Adjust the tone, style, and complexity of your writing to suit any context, whether formal, casual, technical, or creative, for a perfect fit.",
                },
                {
                  icon: "🌐",
                  title: "Wide File and Language Compatibility",
                  desc: "MindNode AI works with various file formats such as DOCX, PDF, and TXT, and provides high-quality results in multiple languages.",
                },
                {
                  icon: "✅",
                  title: "Unique, Plagiarism-Free Output",
                  desc: "All content generated by MindNode AI is 100% original, guaranteeing fresh and plagiarism-free results ready for immediate use.",
                },
                {
                  icon: "🧩",
                  title: "Context-Aware Refinement",
                  desc: "MindNode AI enhances the clarity and flow of your content, improving readability while preserving the core ideas and intent.",
                },
                {
                  icon: "📚",
                  title: "Perfect for Every Audience",
                  desc: "From academic papers to business reports, MindNode AI adapts to your needs, transforming complex text into simple, easy-to-understand writing.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is MindNode AI?",
                  a: "MindNode AI is an innovative platform designed to enhance and refine your content with precision, ideal for a wide range of uses including professional, creative, and academic writing.",
                },
                {
                  q: "How does MindNode AI work?",
                  a: "MindNode AI processes your text and adjusts it according to your preferences, whether by altering tone, summarizing information, or restructuring paragraphs to improve clarity and impact.",
                },
                {
                  q: "Is the content from MindNode AI free of copyright issues?",
                  a: "Yes, every piece of content created by MindNode AI is fully original and free from copyright concerns, ensuring it is safe for any type of use.",
                },
                {
                  q: "Can I customize how MindNode AI edits my content?",
                  a: "Yes, you have full control over customizing aspects such as tone, style, and complexity to match your specific needs, whether for business, casual, or academic purposes.",
                },
                {
                  q: "Can MindNode AI handle large documents?",
                  a: "Absolutely. MindNode AI is designed to efficiently process large documents, including detailed reports and academic papers, without any issues.",
                },
                {
                  q: "What file formats are supported by MindNode AI?",
                  a: "MindNode AI supports various file formats such as DOCX, PDF, and TXT, making it easy to integrate with your existing documents.",
                },
                {
                  q: "Is MindNode AI free to use?",
                  a: "MindNode AI offers both a free version with basic editing tools and a premium version that unlocks advanced features and greater customization options.",
                },
                {
                  q: "Can I export my content after editing it?",
                  a: "Yes, once your content is edited, you can export it or copy it in the format of your choice based on your subscription plan.",
                },
                {
                  q: "Is MindNode AI suitable for students?",
                  a: "Yes, students can benefit from MindNode AI for rewriting essays, summarizing textbooks, and improving academic writing.",
                },
                {
                  q: "Does MindNode AI ensure plagiarism-free output?",
                  a: "Yes, all content generated by MindNode AI is 100% original, ensuring no plagiarism issues.",
                },
                {
                  q: "Is MindNode AI user-friendly?",
                  a: "Yes, the platform is intuitive and accessible for everyone, regardless of technical expertise or writing experience.",
                },
                {
                  q: "Can I set a specific tone for my content?",
                  a: "Yes, MindNode AI allows you to select from various tones, such as formal, casual, academic, or conversational, to meet your needs.",
                },
                {
                  q: "Can businesses use MindNode AI?",
                  a: "Definitely! MindNode AI is perfect for businesses to generate high-quality reports, proposals, emails, and marketing content quickly.",
                },
                {
                  q: "Does MindNode AI store my text or files?",
                  a: "No, MindNode AI respects your privacy and does not retain any content after the editing process is completed.",
                },
                {
                  q: "Can I access MindNode AI from my mobile device?",
                  a: "Yes, MindNode AI is fully responsive and accessible on any device with an internet connection.",
                },
                {
                  q: "Is technical knowledge required to use MindNode AI?",
                  a: "No, MindNode AI is designed to be user-friendly and requires no technical expertise.",
                },
                {
                  q: "Does MindNode AI only paraphrase content?",
                  a: "No, MindNode AI goes beyond paraphrasing; it can restructure content entirely to improve readability, coherence, and engagement while keeping the core message intact.",
                },
                {
                  q: "How quickly does MindNode AI rewrite content?",
                  a: "MindNode AI is extremely fast, often processing content revisions in just a few seconds.",
                },
                {
                  q: "Do I need to install anything to use MindNode AI?",
                  a: "No installation required! MindNode AI is entirely cloud-based, accessible through any web browser.",
                },
                {
                  q: "Where can I get support for MindNode AI?",
                  a: "You can contact our support team through the help center or contact form on the MindNode AI website.",
                },
                {
                  q: "Can MindNode AI be used for creative writing?",
                  a: "Yes, MindNode AI is also great for rewriting creative content like blogs, articles, and stories, offering fresh perspectives while retaining original ideas.",
                },
                {
                  q: "Can I use MindNode AI to summarize long texts?",
                  a: "Yes, MindNode AI is effective at summarizing lengthy content, distilling key points and main ideas into concise, readable summaries.",
                },
                {
                  q: "Is MindNode AI useful for content marketers?",
                  a: "Absolutely! Content marketers can leverage MindNode AI to quickly create unique and compelling marketing copy, social media posts, and advertisements.",
                },
                {
                  q: "How secure is MindNode AI?",
                  a: "MindNode AI prioritizes security by ensuring that all content processing is done securely, with no exposure of your data.",
                },
                {
                  q: "Can MindNode AI handle multilingual content?",
                  a: "Yes, MindNode AI can work with content in multiple languages, making it an excellent choice for international content creation.",
                },
                {
                  q: "Does MindNode AI offer any integrations with other tools?",
                  a: "Yes, MindNode AI integrates with popular content management systems and document processing tools, streamlining your workflow.",
                },
                {
                  q: "Is MindNode AI suitable for eCommerce content?",
                  a: "Yes, MindNode AI is ideal for creating and refining product descriptions, reviews, and other eCommerce-related content to keep it fresh and engaging.",
                },
                {
                  q: "Can MindNode AI help with SEO content?",
                  a: "Definitely! MindNode AI can generate SEO-optimized content, ensuring it is both search-engine friendly and engaging for readers.",
                },
                {
                  q: "Can I adjust the complexity of my content with MindNode AI?",
                  a: "Yes, you can adjust the complexity of your output to suit your audience, whether you need simple language or more technical terminology.",
                },
                {
                  q: "Can I use MindNode AI for content rephrasing in legal documents?",
                  a: "While MindNode AI is great for general content editing, legal documents often require professional legal expertise for accuracy and precision.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src={mindnodeSS1}
                alt="mindnode"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img

                src={mindnodeSS2}

                alt="mindnode"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>MindNode AI</strong> Is the Ideal Solution for
                    Precision, Speed, and Creative Content Enhancement
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>MindNode AI</strong> transforms the content creation
                    process, offering speed, precision, and creativity without
                    sacrificing quality. Whether you're polishing professional
                    reports, composing emails, or refining academic work, here’s
                    why MindNode AI is your go-to solution:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Advanced Content Refinement:</strong> Seamlessly
                      blends clarity with creativity, ensuring that your content
                      meets both functional and aesthetic needs.
                    </li>
                    <li className="mb-3">
                      <strong>100% Unique Output:</strong> Guarantees fresh,
                      plagiarism-free content that can be used for any purpose,
                      from professional reports to casual blog posts.
                    </li>
                    <li className="mb-3">
                      <strong>Flexible Tone Adaptation:</strong> Tailors your
                      writing style to match your desired tone, whether it's
                      formal, casual, persuasive, or informative.
                    </li>
                    <li className="mb-3">
                      <strong>Instant Results:</strong> Produces polished text
                      in mere seconds, allowing you to stay on schedule even
                      with tight deadlines.
                    </li>
                    <li className="mb-3">
                      <strong>Simple, Intuitive Interface:</strong> Easy to use
                      for both seasoned writers and beginners, ensuring a smooth
                      and efficient experience.
                    </li>
                    <li className="mb-3">
                      <strong>Highly Versatile:</strong> Perfect for a variety
                      of content types, from drafting emails and writing
                      articles to creating marketing copy and technical
                      documents.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Try <strong>MindNode AI</strong> — Enhance Your Writing
                      with Precision, Speed, and Creativity
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>MindNode AI</strong> Is a Powerful and Innovative Tool
              for Efficient Content Rewriting
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>MindNode AI</strong> streamlines the content creation
              process by offering enhanced rewording, clarity, and refinement,
              all while ensuring originality and plagiarism-free output.
            </p>

            {/* MindNode AI Section */}
            <div className="row justify-content-center gap-2 mb-5">
              {/* MindNode AI Pros */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">
                  ✅ MindNode AI - Pros
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Flexible Tone Options:</strong> Offers various
                    writing tones (formal, informal, technical, creative) to
                    match the content type.
                  </li>
                  <li className="mb-2">
                    <strong>High-Quality, Plagiarism-Free Content:</strong>{" "}
                    Guarantees that all rewritten material is unique, ensuring
                    it meets project standards.
                  </li>
                  <li className="mb-2">
                    <strong>Real-Time Content Refinements:</strong> Instantly
                    enhances content, adjusting sentence structures and word
                    choices to improve readability.
                  </li>
                  <li className="mb-2">
                    <strong>Context-Aware Adjustments:</strong> Ensures the
                    original meaning is preserved while enhancing clarity, tone,
                    and overall engagement.
                  </li>
                  <li className="mb-2">
                    <strong>Versatile Across Content Types:</strong> Ideal for
                    writing emails, reports, blog posts, and academic papers,
                    making it a versatile tool for various content formats.
                  </li>
                </ul>
              </div>

              {/* MindNode AI Cons */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">
                  ⚠️ MindNode AI - Cons
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Requires a Stable Internet Connection:</strong>{" "}
                    MindNode AI operates solely online, which can limit access
                    in offline situations.
                  </li>
                  <li className="mb-2">
                    <strong>Not Designed for Fiction Writing:</strong> Primarily
                    suited for professional, academic, and technical writing
                    rather than creative storytelling.
                  </li>
                  <li className="mb-2">
                    <strong>May Oversimplify Complex Concepts:</strong> In
                    certain cases, it may reduce the depth of technical or
                    academic writing, potentially omitting important details.
                  </li>
                  <li className="mb-2">
                    <strong>Lack of Automated Citation Feature:</strong>{" "}
                    MindNode AI does not automatically generate citations,
                    requiring users to handle references manually.
                  </li>
                  <li className="mb-2">
                    <strong>Advanced Features Are Behind a Paywall:</strong>{" "}
                    Premium options, such as bulk processing and customizable
                    settings, are only available in the paid version.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Discover Leading Alternatives to MindNode AI for Optimized Content
              Rewriting
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>MindNode AI</strong> excels at providing accurate
              content transformations, several other tools bring unique
              capabilities for text simplification, paraphrasing, and
              summarization—each designed to cater to distinct content needs and
              writing preferences.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #007bff",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>MindNode AI</strong>: Known for its precise content
                    analysis and rewriting capabilities, MindNode AI maintains
                    the core message while enhancing tone, clarity, and style to
                    fit diverse writing contexts.
                  </li>
                  <li className="mb-2">
                    <strong>ClearText</strong>: Best for simplifying complex
                    text, this tool transforms technical or jargon-heavy content
                    into straightforward, easily digestible language.
                  </li>
                  <li className="mb-2">
                    <strong>RefinedEdge</strong>: Specializes in rewriting
                    technical papers and academic work, offering improvements in
                    structure and clarity to make intricate ideas more
                    approachable.
                  </li>
                  <li className="mb-2">
                    <strong>QuickSummary</strong>: Designed for users who need
                    to distill long-form content into concise, key insights,
                    perfect for reports and lengthy articles.
                  </li>
                  <li className="mb-2">
                    <strong>PhraseFlex</strong>: Provides a variety of rewriting
                    options, from professional to casual tones, to adapt your
                    content for different audiences or contexts.
                  </li>
                  <li className="mb-2">
                    <strong>BrandScript</strong>: Tailored for marketing and
                    content creators, BrandScript adjusts the tone, structure,
                    and style of your content to align with brand voice and
                    audience preferences.
                  </li>
                  <li className="mb-2">
                    <strong>BriefIt</strong>: Efficiently condenses long
                    documents, articles, and reports, making them more scannable
                    while preserving the essential points.
                  </li>
                  <li className="mb-2">
                    <strong>RewriteMaster</strong>: Offers a high degree of
                    customization, allowing users to control the complexity,
                    creativity, and flow of rewritten content to suit various
                    needs.
                  </li>
                  <li className="mb-2">
                    <strong>DocSimplifier</strong>: Ideal for turning dense,
                    technical documents—such as legal or scientific papers—into
                    easily understandable, plain language text.
                  </li>
                  <li className="mb-2">
                    <strong>InstantRephrase</strong>: Automatically generates
                    concise summaries for long paragraphs or articles, providing
                    quick, digestible insights without missing the core message.
                  </li>
                  <li className="mb-2">
                    <strong>EasyWrite</strong>: Helps streamline content for
                    various purposes, from business reports to creative writing,
                    enhancing both readability and coherence.
                  </li>
                  <li className="mb-2">
                    <strong>PrecisionWrite</strong>: Designed for professionals,
                    PrecisionWrite refines technical documents, presentations,
                    and research papers, ensuring clarity and accuracy.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
         <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
         <div className="row d-flex align-items-center justify-content-between mb-1 flex-column flex-md-row">
  {/* Image First on Mobile, Right Side on Desktop */}
 <div className="col-12 col-md-6 order-1 order-md-2 mb-3 mb-md-0 text-center">
  <img
    src={mindnodeImg}
    alt="MindNode AI"
    className="img-fluid"
    style={{ width: "100%", height: "auto", objectFit: "contain" }}
  />
</div>


  {/* Text Second on Mobile, Left Side on Desktop */}
  <div className="col-12 col-md-6 order-2 order-md-1" style={{ paddingRight: "30px" }}>
    <p className="text-primary">Write better, faster</p>
    <h1>MindNode AI:</h1>
    <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
    <p>
      MindNode AI is a cutting-edge mind mapping tool that integrates
      artificial intelligence to help users organize ideas, prioritize
      tasks, and manage projects effectively. Whether you're
      brainstorming new ideas, planning a project, or tracking tasks,
      MindNode AI provides an intuitive, visual approach that enhances
      creativity and boosts productivity. Its AI-powered features
      automate task prioritization, improve decision-making, and
      facilitate team collaboration, making it an ideal tool for
      individuals, teams, and businesses alike.
    </p>
    <a
      href="https://www.mindnode.com/"
      rel="noopener noreferrer"
      className="btn btn-primary me-2"
    >
      Explore Tool
    </a>
  </div>
</div>


          <section style={{ backgroundColor: "#2e3b4e", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Powered by Precision—Effortless Content Transformation with
                MindNode AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                See How MindNode AI Converts Complex Ideas into Clear,
                Purposeful Content
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                MindNode AI helps transform dense, specialized text into clear,
                easily digestible language, while maintaining your original
                intent and guaranteeing copyright-free content.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .mindnode-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      In-Depth Content Analysis
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      MindNode AI thoroughly analyzes your content, capturing
                      its key concepts and context, ensuring accurate and
                      refined transformations aligned with your goals.
                    </p>
                    <div className="mindnode-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .mindnode-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Customizable Rewriting Options
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Tailor your content's style and tone to fit specific
                      requirements—be it professional, casual, or
                      technical—without needing any advanced expertise.
                    </p>
                    <div className="mindnode-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .mindnode-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Unique, Ready-to-Use Content
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Every piece of content generated by MindNode AI is
                      completely unique, ensuring you're free from plagiarism
                      risks, ready for any purpose.
                    </p>
                    <div className="mindnode-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          
        </div>
      </div>
    </>
  );
};

export default MindNode;
