import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";
// import scappleSS1 from '../../../../public/assets/Img/Ai for Mind Mapping/scappleSS1.png';
// import scappleSS2 from '../../../../public/assets/Img/Ai for Mind Mapping/scappleSS2.png';
import scappleImg from '../../../../public/assets/Img/Ai for Mind Mapping/6.png';

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const Scapple = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="Scapple AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Effortlessly Enhance and Personalize Your Text with Scapple AI
                </p>
                <h3>
                  Advanced, Adaptive Content Enhancement for Every Writing
                  Requirement
                </h3>
              </div>
              {[
                {
                  icon: "🔄",
                  title: "Intelligent Content Refinement",
                  desc: "Scapple AI refines your content with ease, ensuring clarity, structure, and relevance, all while keeping the original message intact.",
                },
                {
                  icon: "🎨",
                  title: "Customizable Tone and Style",
                  desc: "Modify the tone, style, and complexity of your writing to fit any context—whether formal, casual, professional, or creative.",
                },
                {
                  icon: "🌐",
                  title: "Broad Compatibility with File Formats and Languages",
                  desc: "Scapple AI supports various file formats such as DOCX, PDF, and TXT, and delivers high-quality results in multiple languages.",
                },
                {
                  icon: "✅",
                  title: "100% Unique and Plagiarism-Free",
                  desc: "Every piece of content generated by Scapple AI is completely original and free from plagiarism, ready for immediate use.",
                },
                {
                  icon: "🧩",
                  title: "Context-Sensitive Refinement",
                  desc: "Scapple AI enhances the clarity and flow of your writing, improving readability while preserving the core ideas and message.",
                },
                {
                  icon: "📚",
                  title: "Ideal for All Types of Writing",
                  desc: "From academic essays to corporate reports, Scapple AI adapts to your needs, turning complex content into clear, comprehensible text.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is Scapple AI?",
                  a: "Scapple AI is an advanced platform that enhances your content with speed and precision, making it ideal for professional, creative, and academic writing tasks.",
                },
                {
                  q: "How does Scapple AI work?",
                  a: "Scapple AI processes your input and customizes the output based on your preferences, adjusting tone, simplifying complex ideas, or reorganizing content to enhance readability.",
                },
                {
                  q: "Is the content from Scapple AI free of copyright issues?",
                  a: "Yes, Scapple AI guarantees that all generated content is fully original and free of copyright concerns, ensuring it is safe for any use.",
                },
                {
                  q: "Can I customize how Scapple AI edits my content?",
                  a: "Yes, you can tailor the tone, style, and level of complexity to suit your specific needs, whether for business communication, casual writing, or academic papers.",
                },
                {
                  q: "Can Scapple AI handle large documents?",
                  a: "Yes, Scapple AI is designed to efficiently process large documents, including detailed reports, academic papers, and extensive articles.",
                },
                {
                  q: "What file formats are supported by Scapple AI?",
                  a: "Scapple AI supports several popular file formats, including DOCX, PDF, and TXT, making it easy to work with your existing content.",
                },
                {
                  q: "Is Scapple AI free to use?",
                  a: "Scapple AI offers a free version with basic features, along with a premium plan that unlocks advanced editing tools and greater customization options.",
                },
                {
                  q: "Can I export my content after editing it?",
                  a: "Yes, Scapple AI allows you to export your edited content in a format of your choice, depending on your subscription plan.",
                },
                {
                  q: "Is Scapple AI suitable for students?",
                  a: "Yes, students can use Scapple AI to improve their essays, summarize study materials, and refine their academic writing.",
                },
                {
                  q: "Does Scapple AI ensure plagiarism-free output?",
                  a: "Yes, all content generated by Scapple AI is 100% original and free from plagiarism.",
                },
                {
                  q: "Is Scapple AI user-friendly?",
                  a: "Yes, the platform is designed to be intuitive and easy to use, regardless of your writing experience or technical background.",
                },
                {
                  q: "Can I set a specific tone for my content?",
                  a: "Yes, Scapple AI allows you to choose from various tones, such as formal, casual, academic, or conversational, to match your needs.",
                },
                {
                  q: "Can businesses use Scapple AI?",
                  a: "Definitely! Scapple AI is an excellent tool for businesses to generate high-quality reports, marketing content, emails, and proposals quickly.",
                },
                {
                  q: "Does Scapple AI store my text or files?",
                  a: "No, Scapple AI does not store any content after editing, respecting your privacy and ensuring no data retention.",
                },
                {
                  q: "Can I access Scapple AI from my mobile device?",
                  a: "Yes, Scapple AI is fully responsive, meaning you can access and use it on any device with an internet connection.",
                },
                {
                  q: "Is technical knowledge required to use Scapple AI?",
                  a: "No, Scapple AI is designed to be user-friendly, so no technical expertise is required to use it effectively.",
                },
                {
                  q: "Does Scapple AI only paraphrase content?",
                  a: "No, Scapple AI goes beyond simple paraphrasing. It can restructure entire pieces of content for improved clarity, engagement, and flow, while preserving the core message.",
                },
                {
                  q: "How quickly does Scapple AI rewrite content?",
                  a: "Scapple AI is incredibly fast, delivering refined content in just a few seconds.",
                },
                {
                  q: "Do I need to install anything to use Scapple AI?",
                  a: "No installation is necessary. Scapple AI is fully cloud-based and can be accessed directly from any web browser.",
                },
                {
                  q: "Where can I get support for Scapple AI?",
                  a: "You can reach our support team through the help center or contact form available on the Scapple AI website.",
                },
                {
                  q: "Can Scapple AI be used for creative writing?",
                  a: "Yes, Scapple AI is also a great tool for creative writing, such as drafting blogs, stories, or articles, offering fresh ideas while staying true to your original concepts.",
                },
                {
                  q: "Can I use Scapple AI to summarize long texts?",
                  a: "Yes, Scapple AI is effective at summarizing lengthy content, breaking it down into concise, key points and readable summaries.",
                },
                {
                  q: "Is Scapple AI useful for content marketers?",
                  a: "Absolutely! Content marketers can use Scapple AI to quickly generate engaging and unique marketing copy, social media posts, and advertisements.",
                },
                {
                  q: "How secure is Scapple AI?",
                  a: "Scapple AI places a high priority on security, ensuring that all content processing is done securely without compromising your data.",
                },
                {
                  q: "Can Scapple AI handle multilingual content?",
                  a: "Yes, Scapple AI can work with content in multiple languages, making it an excellent choice for creating international content.",
                },
                {
                  q: "Does Scapple AI offer any integrations with other tools?",
                  a: "Yes, Scapple AI integrates with popular content management systems and other document processing tools to streamline your workflow.",
                },
                {
                  q: "Is Scapple AI suitable for eCommerce content?",
                  a: "Yes, Scapple AI is perfect for creating and refining eCommerce content, such as product descriptions, reviews, and advertisements, keeping it engaging and fresh.",
                },
                {
                  q: "Can Scapple AI help with SEO content?",
                  a: "Yes, Scapple AI can create SEO-friendly content, ensuring that it is optimized for search engines and engaging for readers.",
                },
                {
                  q: "Can I adjust the complexity of my content with Scapple AI?",
                  a: "Yes, you can adjust the complexity of your content, whether you need simple, easy-to-understand language or more technical, in-depth terminology.",
                },
                {
                  q: "Can I use Scapple AI for content rephrasing in legal documents?",
                  a: "While Scapple AI can assist with general content editing, we recommend professional legal expertise for the accuracy and precision required in legal documents.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src={scappleSS1}
                alt="scapple"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img

                src={scappleSS2}

                alt="scapple"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>Scapple AI</strong> is the Ultimate Tool for
                    Streamlined Content Refinement and Creative Enhancement
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>Scapple AI</strong> transforms the writing process
                    by combining speed, precision, and creative flair, offering
                    a seamless experience for both professional and personal
                    writing needs. Whether you're drafting emails, perfecting
                    reports, or creating content for your blog, here's why
                    Scapple AI is the perfect solution:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Effortless Content Enhancement:</strong> Balances
                      clarity and creativity, improving the structure and flow
                      of your text without compromising your original message.
                    </li>
                    <li className="mb-3">
                      <strong>100% Originality Guaranteed:</strong> Delivers
                      fresh, plagiarism-free content that is suitable for any
                      project—whether formal or casual.
                    </li>
                    <li className="mb-3">
                      <strong>Customizable Writing Styles:</strong> Adjusts tone
                      and voice to suit your needs, whether you’re writing
                      persuasively, informally, or in a professional tone.
                    </li>
                    <li className="mb-3">
                      <strong>Instant Content Refinement:</strong> Generates
                      polished, refined content within seconds, helping you stay
                      ahead of deadlines without sacrificing quality.
                    </li>
                    <li className="mb-3">
                      <strong>User-Friendly Interface:</strong> Designed to be
                      intuitive and easy to navigate, ensuring a smooth
                      experience for both experienced writers and newcomers.
                    </li>
                    <li className="mb-3">
                      <strong>Versatile and Multi-Purpose:</strong> Ideal for a
                      wide range of content, including business emails, blog
                      articles, technical documentation, and creative writing
                      projects.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Try <strong>Scapple AI</strong> — Unlock Your Writing
                      Potential with Speed, Precision, and Creativity
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>Scapple AI</strong> Stands Out as a Powerful and
              Innovative Tool for Content Rewriting
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>Scapple AI</strong> revolutionizes content creation by
              refining writing, enhancing clarity, and ensuring high-quality,
              unique outputs—all with minimal effort.
            </p>

            {/* Scapple AI Section */}
            <div className="row justify-content-center gap-2 mb-5">
              {/* Scapple AI Pros */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">
                  ✅ Scapple AI - Pros
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Customizable Tone and Style:</strong> Provides a
                    variety of tone options, from formal to casual, ensuring the
                    content matches the intended purpose.
                  </li>
                  <li className="mb-2">
                    <strong>High-Quality, Original Content:</strong> Guarantees
                    that the rewritten text is unique, free from plagiarism, and
                    meets high-quality standards.
                  </li>
                  <li className="mb-2">
                    <strong>Instant Content Enhancement:</strong> Quickly
                    analyzes and refines content in real time, improving
                    readability and sentence structure for better flow.
                  </li>
                  <li className="mb-2">
                    <strong>Context-Sensitive Rewriting:</strong> Adjusts
                    writing while preserving the original meaning, improving
                    tone, clarity, and engagement in the process.
                  </li>
                  <li className="mb-2">
                    <strong>Multi-Use Flexibility:</strong> Ideal for a variety
                    of content formats including blogs, emails, academic papers,
                    and reports, making it a versatile tool for different needs.
                  </li>
                </ul>
              </div>

              {/* Scapple AI Cons */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #28a745",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">
                  ⚠️ Scapple AI - Cons
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Internet Dependency:</strong> Scapple AI is an
                    online tool, meaning a stable internet connection is
                    required to access its features.
                  </li>
                  <li className="mb-2">
                    <strong>Not Suitable for Fiction Writing:</strong> Best
                    suited for professional, technical, or academic content,
                    Scapple AI is less effective for creative writing like
                    storytelling.
                  </li>
                  <li className="mb-2">
                    <strong>Potential Over-Simplification:</strong> For highly
                    complex topics, there may be cases where Scapple AI
                    simplifies content too much, leaving out important nuances.
                  </li>
                  <li className="mb-2">
                    <strong>No Automatic Citation Generation:</strong> Unlike
                    some other tools, Scapple AI does not generate citations,
                    requiring users to manually handle references.
                  </li>
                  <li className="mb-2">
                    <strong>Premium Features Are Behind a Paywall:</strong> Some
                    advanced features, like bulk processing and advanced
                    customization, are only available in the paid version.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Explore the Top Alternatives to Scapple AI for Effective Content
              Transformation
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>Scapple AI</strong> is renowned for its ability to
              rework and enhance content while preserving meaning, a variety of
              other tools also specialize in content simplification,
              paraphrasing, and summarization, each with its own set of
              strengths.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #007bff",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Scapple AI</strong>: Known for its intelligent
                    content transformation, Scapple AI keeps the essence of your
                    writing intact while optimizing clarity, tone, and
                    engagement for various contexts.
                  </li>
                  <li className="mb-2">
                    <strong>SimpleText</strong>: Ideal for simplifying overly
                    technical language, SimpleText turns complex jargon into
                    clear and accessible language for any audience.
                  </li>
                  <li className="mb-2">
                    <strong>AcademicRewrite</strong>: Tailored for academic
                    writing, AcademicRewrite specializes in enhancing research
                    papers and complex articles for improved readability and
                    coherence.
                  </li>
                  <li className="mb-2">
                    <strong>ContentCrunch</strong>: Focused on breaking down
                    long-form articles and research into digestible summaries,
                    ContentCrunch makes it easier to grasp key ideas without the
                    need to read everything.
                  </li>
                  <li className="mb-2">
                    <strong>RephraseIt</strong>: This tool offers flexibility in
                    rewriting text across a range of tones—be it formal,
                    informal, or technical—ensuring it suits the intended
                    audience.
                  </li>
                  <li className="mb-2">
                    <strong>BrandEcho</strong>: Best suited for marketers and
                    content creators, BrandEcho adapts your writing style to
                    match brand guidelines and audience expectations.
                  </li>
                  <li className="mb-2">
                    <strong>TextShortener</strong>: Perfect for reducing lengthy
                    documents while keeping the essential details intact,
                    TextShortener is ideal for reports and documents that need
                    to be more concise.
                  </li>
                  <li className="mb-2">
                    <strong>WriteMaster</strong>: A highly customizable tool,
                    WriteMaster allows users to adjust writing complexity and
                    creativity, giving more control over content tone and
                    structure.
                  </li>
                  <li className="mb-2">
                    <strong>DocSimplify</strong>: Excellent for translating
                    dense, specialized documents, like legal or scientific
                    content, into easy-to-understand language without
                    sacrificing technical accuracy.
                  </li>
                  <li className="mb-2">
                    <strong>QuickSummarizer</strong>: Designed for fast,
                    efficient summarization, QuickSummarizer helps distill
                    complex texts into their core ideas, making them quick to
                    read and comprehend.
                  </li>
                  <li className="mb-2">
                    <strong>ContentFlow</strong>: This tool enhances the flow
                    and coherence of content, whether for reports, business
                    writing, or creative works, making them more structured and
                    engaging.
                  </li>
                  <li className="mb-2">
                    <strong>PrecisionEditor</strong>: Specially crafted for
                    professionals, PrecisionEditor sharpens technical content
                    and research papers, ensuring they are clear, concise, and
                    well-organized.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        {/* <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a> */}
         <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none  mt-3 ml-3 py-1 px-2 ms-5 border rounded-sm"
        >
          <i className="bi bi-arrow-left me-2"></i>Back  {" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
        <div className="row d-flex align-items-center justify-content-between mb-1 flex-column flex-md-row">
  {/* Image First on Mobile, Right on Desktop */}
<div className="col-12 col-md-6 order-1 order-md-2 text-center mb-3 mb-md-0" style={{ paddingLeft: 0, paddingRight: 0 }}>
  <img
    src={scappleImg}
    alt="Scapple AI"
    className="img-fluid"
    style={{
      width: "100%",         
      height: "auto",        
      maxHeight: "300px",    
      objectFit: "cover"
    }}
  />
</div>


  {/* Text Second on Mobile, Left on Desktop */}
  <div className="col-12 col-md-6 order-2 order-md-1" style={{ paddingRight: "30px" }}>
    <p className="text-primary">Write better, faster</p>
    <h1>Scapple AI:</h1>
    <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
    <p>
      Scapple AI is a powerful mind mapping and brainstorming tool
      designed to help individuals and teams organize their ideas,
      manage tasks, and plan projects more effectively. Integrating
      artificial intelligence into its mind mapping software, Scapple
      AI offers an innovative way to prioritize tasks, enhance
      collaboration, and visualize concepts, making it a go-to
      solution for creative professionals, business planners, and
      project managers. Whether you are brainstorming, planning, or
      managing tasks, Scapple AI provides a seamless, intuitive
      platform to maximize productivity and foster creativity.
    </p>
    <a
      href="https://www.literatureandlatte.com/scapple/"
      rel="noopener noreferrer"
      className="btn btn-primary me-2"
    >
      Explore Tool
    </a>
  </div>
</div>


          <section style={{ backgroundColor: "#2e3b4e", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Empowering Precision—Transform Your Ideas Seamlessly with
                Scapple AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                Discover How Scapple AI Converts Complex Thoughts into Clear,
                Impactful Content
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                Scapple AI simplifies dense, technical language into clear and
                engaging content, while keeping your core message intact and
                ensuring all content is original and copyright-free.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .scapple-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Thorough Content Analysis
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Scapple AI thoroughly analyzes your content, extracting
                      its key themes and nuances to ensure an accurate
                      transformation that meets your objectives.
                    </p>
                    <div className="scapple-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .scapple-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Tailored Content Customization
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Customize your content’s tone, style, and complexity to
                      align with your audience’s needs—be it professional,
                      casual, or technical.
                    </p>
                    <div className="scapple-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0062cc",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .scapple-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      100% Unique, Ready-to-Use Output
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      All content created by Scapple AI is completely original,
                      ensuring you never face plagiarism issues and are ready to
                      use the results instantly.
                    </p>
                    <div className="scapple-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          
        </div>
      </div>
    </>
  );
};

export default Scapple;
