import React, { useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../ImageMindAI.css"; // <-- custom CSS file import
import { Container, Row, Col, Button, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";
import Logo from "../../../Images/logo[2].png";
import deatilimage from "../../../Images/DetailImage.png";

// review section data
const reviews = [
  {
    name: "Alex Johnson",
    date: "April 15, 2025",
    review:
      "This tool has completely transformed my workflow. The AI capabilities are far beyond what I expected and the interface is intuitive.",
    rating: 5,
  },
  {
    name: "Sarah Miller",
    date: "April 10, 2025",
    review:
      "Very powerful tool with great features. The only reason I’m not giving 5 stars is because of the learning curve for some advanced features.",
    rating: 4,
  },
  {
    name: "David Chen",
    date: "April 3, 2025",
    review:
      "Worth every penny! The customer support is exceptional and the tool itself has saved me countless hours of work.",
    rating: 5,
  },
  {
    name: "Emma Wilson",
    date: "March 28, 2025",
    review:
      "Good tool overall, but I’ve experienced some performance issues with larger projects. Hope they improve this in future updates.",
    rating: 3,
  },
];

const ratingBreakdown = {
  "5 stars": 70,
  "4 stars": 20,
  "3 stars": 7,
  "2 stars": 2,
  "1 star": 1,
};

// Technical details styles
const styles = {
  section: {
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    minHeight: "100vh",
    padding: "60px 0",
  },
  card: {
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    padding: "30px",
    height: "100%",
  },
  smallText: {
    fontSize: "0.95rem",
  },
  button: {
    backgroundColor: "#238636",
    borderColor: "#238636",
  },
  buttonHover: {
    backgroundColor: "#2ea043",
    borderColor: "#2ea043",
  },
};
const XMind = () => {
  const [activeTab, setActiveTab] = useState("Features"); // Set the default
  //  active tab as 'features'
  const [showAllFaqs, setShowAllFaqs] = useState(false);

  const renderTabContent = () => {
    switch (activeTab) {
      case "Features":
        return (
          <section aria-label="XMind AI Features">
            <div className="row g-4">
              <div className="text-center mb-4">
                <p className="text-primary">
                  Effortlessly Refine and Customize Your Content with XMind AI
                </p>
                <h3>
                  Advanced, Tailored Text Enhancement Engine for Every Content
                  Need
                </h3>
              </div>
              {[
                {
                  icon: "🔄",
                  title: "Intelligent Text Reworking",
                  desc: "XMind AI automatically refines your content, adapting it for clarity, organization, or specific audience needs without losing your original message.",
                },
                {
                  icon: "🎨",
                  title: "Customizable Tone and Style",
                  desc: "Easily adjust the tone and complexity of your text—whether professional, casual, technical, or creative—ensuring it resonates with your target audience.",
                },
                {
                  icon: "🌐",
                  title: "Universal File & Language Support",
                  desc: "XMind AI supports a wide range of file types, including DOCX, PDF, and plain text, and can generate contextually accurate results in multiple languages.",
                },
                {
                  icon: "✅",
                  title: "Completely Original Content",
                  desc: "All content generated by XMind AI is 100% unique, ensuring no concerns about plagiarism or copyright infringement, ready for immediate use.",
                },
                {
                  icon: "🧩",
                  title: "Context-Aware Enhancements",
                  desc: "Preserves the core meaning of your text while improving readability and clarity, making your content more accessible and engaging for readers.",
                },
                {
                  icon: "📚",
                  title: "Ideal for All Audiences",
                  desc: "Whether you're working on academic papers or corporate reports, XMind AI helps transform complex text into clear, concise, and easy-to-read versions in seconds.",
                },
              ].map((feature, index) => (
                <div className="col-md-4" key={index}>
                  <div className="custom-card text-light p-4 h-100 border border-primary rounded">
                    <div
                      className="icon mb-3 fs-3"
                      role="img"
                      aria-label="Feature Icon"
                    >
                      {feature.icon}
                    </div>
                    <h5 className="fw-bold">{feature.title}</h5>
                    <p>{feature.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );

      case "FAQs":
        return (
          <div className="faq-section container py-4">
            <h3 className="text-center text-white mb-4 text-primary">
              Frequently Asked Questions
            </h3>

            <div className="accordion" id="faqAccordion">
              {[
                {
                  q: "What is XMind AI?",
                  a: "XMind AI is a powerful platform designed to enhance, simplify, and tailor your content with precision, making it ideal for personal, professional, and creative use.",
                },
                {
                  q: "How does XMind AI work?",
                  a: "XMind AI analyzes your provided text and modifies it according to your specified preferences, whether it’s adjusting the tone, condensing ideas, or rewording entire sections to maintain freshness and clarity.",
                },
                {
                  q: "Is the content from XMind AI free of copyright issues?",
                  a: "Yes, every piece of content generated by XMind AI is completely original and free from copyright concerns, making it safe for any kind of use.",
                },
                {
                  q: "Can I customize how XMind AI edits my content?",
                  a: "Absolutely. You can tailor elements like tone, style, and complexity to suit your specific needs, whether for professional, casual, or academic purposes.",
                },
                {
                  q: "Can XMind AI handle large documents?",
                  a: "Yes, XMind AI is optimized for processing long documents, including research papers and detailed articles, with ease.",
                },
                {
                  q: "What file formats are supported by XMind AI?",
                  a: "XMind AI supports a variety of file formats, such as DOCX, PDF, and TXT, ensuring smooth integration with your existing documents.",
                },
                {
                  q: "Is XMind AI free to use?",
                  a: "XMind AI offers both a free and premium version. The free version includes basic editing tools, while the premium version unlocks advanced features and customization options.",
                },
                {
                  q: "Can I export my content after editing it?",
                  a: "Yes, you can export or copy your edited content in your preferred format, depending on your subscription level.",
                },
                {
                  q: "Is XMind AI suitable for students?",
                  a: "Yes, students can benefit from XMind AI, especially for rewriting essays, summarizing academic materials, and refining scholarly writing.",
                },
                {
                  q: "Does XMind AI ensure plagiarism-free output?",
                  a: "Yes, all content generated by XMind AI is 100% original, removing any risks of plagiarism.",
                },
                {
                  q: "Is XMind AI user-friendly?",
                  a: "Yes, the platform is designed to be intuitive and accessible to everyone, whether you’re a beginner or an expert.",
                },
                {
                  q: "Can I set a specific tone for my content?",
                  a: "Yes, XMind AI lets you choose from a variety of tones, such as formal, casual, academic, or conversational, to suit your needs.",
                },
                {
                  q: "Can businesses use XMind AI?",
                  a: "Definitely. XMind AI is ideal for businesses to create polished reports, proposals, emails, and marketing materials with ease.",
                },
                {
                  q: "Does XMind AI store my text or files?",
                  a: "No, XMind AI respects your privacy and does not store any of your content after the editing process.",
                },
                {
                  q: "Can I access XMind AI from my mobile device?",
                  a: "Yes, XMind AI is fully responsive and can be accessed on any device with internet connectivity.",
                },
                {
                  q: "Is technical knowledge required to use XMind AI?",
                  a: "No, XMind AI is designed for simplicity, making it accessible to users without technical expertise.",
                },
                {
                  q: "Does XMind AI only paraphrase content?",
                  a: "No, XMind AI can both paraphrase and completely restructure content to improve clarity, coherence, and engagement while maintaining the original message.",
                },
                {
                  q: "How quickly does XMind AI rewrite content?",
                  a: "XMind AI works incredibly fast, typically processing content revisions in just a few seconds.",
                },
                {
                  q: "Do I need to install anything to use XMind AI?",
                  a: "No installation is required. XMind AI is fully cloud-based and can be accessed directly through your web browser.",
                },
                {
                  q: "Where can I get support for XMind AI?",
                  a: "You can reach our support team through the help center or contact form available on the XMind AI website.",
                },
                {
                  q: "Can XMind AI be used for creative writing?",
                  a: "Yes, XMind AI is also a great tool for rewording creative texts like blogs, articles, and more, providing fresh perspectives while maintaining original ideas.",
                },
                {
                  q: "Can I use XMind AI to summarize long texts?",
                  a: "Yes, XMind AI is highly effective at summarizing lengthy content, preserving key ideas and essential points in a concise manner.",
                },
                {
                  q: "Is XMind AI useful for content marketers?",
                  a: "Absolutely. Content marketers can leverage XMind AI to quickly create unique and compelling versions of marketing content, social media posts, and advertisements.",
                },
                {
                  q: "How secure is XMind AI?",
                  a: "XMind AI prioritizes security by ensuring all content processing is handled securely, with no risk of data exposure.",
                },
                {
                  q: "Can XMind AI handle multilingual content?",
                  a: "Yes, XMind AI can process and rewrite content in multiple languages, making it an excellent tool for international content creation.",
                },
                {
                  q: "Does XMind AI offer any integrations with other tools?",
                  a: "Yes, XMind AI integrates with popular content management systems and document processing tools to help streamline your workflow.",
                },
                {
                  q: "Is XMind AI suitable for eCommerce content?",
                  a: "Yes, XMind AI is perfect for rewriting product descriptions, reviews, and other eCommerce-related content to keep it engaging and fresh.",
                },
                {
                  q: "Can XMind AI help with SEO content?",
                  a: "Absolutely. XMind AI can generate SEO-friendly content that is optimized for search engines while maintaining readability and user engagement.",
                },
                {
                  q: "Can I adjust the complexity of my content with XMind AI?",
                  a: "Yes, you can adjust the complexity of your output to suit your audience, whether you need it simple or more advanced.",
                },
                {
                  q: "Can I use XMind AI for content rephrasing in legal documents?",
                  a: "While XMind AI is excellent for general content editing, legal documents often require professional legal expertise for accuracy and precision.",
                },
              ]

                .map((item, i) => ({ ...item, id: `faq${i}` }))
                .filter((item, i) => showAllFaqs || i < 4)
                .map((item, i) => (
                  <div className="accordion-item mb-3" key={item.id}>
                    <h2 className="accordion-header" id={`heading${item.id}`}>
                      <button
                        className={`accordion-button ${
                          i !== 0 ? "collapsed" : ""
                        }`}
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target={`#collapse${item.id}`}
                        aria-expanded={i === 0 ? "true" : "false"}
                        aria-controls={`collapse${item.id}`}
                        style={{
                          backgroundColor: "#161b22",
                          color: "#c9d1d9",
                          fontWeight: "bold",
                        }}
                      >
                        {item.q}
                      </button>
                    </h2>
                    <div
                      id={`collapse${item.id}`}
                      className={`accordion-collapse collapse ${
                        i === 0 ? "show" : ""
                      }`}
                      aria-labelledby={`heading${item.id}`}
                      data-bs-parent="#faqAccordion"
                    >
                      <div
                        className="accordion-body"
                        style={{
                          backgroundColor: "#0d1117",
                          color: "#c9d1d9",
                          border: "1px solid #238636",
                          borderRadius: "8px",
                          padding: "15px",
                        }}
                      >
                        {item.a}
                      </div>
                    </div>
                  </div>
                ))}

              <div className="text-center mt-4">
                <button
                  className="btn btn-outline-light"
                  onClick={() => setShowAllFaqs(!showAllFaqs)}
                >
                  {showAllFaqs ? "Show Less" : "Read More"}
                </button>
              </div>
            </div>
          </div>
        );

      case "Screenshots":
        return (
          <div className="row g-4">
            <div className="col-md-6">
              <img
                src="https://www.testingcatalog.com/content/images/size/w2000/2024/06/screenshot-app.runwayml.com-2024.06.24-00_36_32--1-.png"
                alt=""
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
            <div className="col-md-6">
              <img
                src="https://www.techspot.com/articles-info/2720/images/2023-08-17-image.jpg"
                className="img-fluid rounded-3  w-100 h-100 object-fit-cover"
              />
            </div>
          </div>
        );

      case "Reviews":
        return (
          <Container style={{ backgroundColor: "black", padding: "20px" }}>
            <Row style={{ justifyContent: "center" }}>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div
                  style={{
                    backgroundColor: "#2f2f2f",
                    padding: "20px",
                    borderRadius: "5px",
                  }}
                >
                  <h4
                    style={{
                      fontSize: "1.5rem",
                      fontWeight: "bold",
                      color: "white",
                    }}
                  >
                    USER REVIEWS
                  </h4>
                  <div className="d-flex align-items-center mb-3">
                    <p className="text-white">4.5 out of 5</p>
                    <p style={{ color: "#6c757d" }}> ⭐⭐⭐⭐⭐</p>
                  </div>
                  <ProgressBar
                    now={ratingBreakdown["5 stars"]}
                    label="5 stars"
                    variant="success"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["4 stars"]}
                    label="4 stars"
                    variant="info"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["3 stars"]}
                    label="3 stars"
                    variant="warning"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["2 stars"]}
                    label="2 stars"
                    variant="danger"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                  <ProgressBar
                    now={ratingBreakdown["1 star"]}
                    label="1 star"
                    variant="secondary"
                    style={{ marginBottom: "20px", height: "30px" }}
                  />
                </div>
              </Col>
              <Col md={12} lg={6} style={{ marginBottom: "20px" }}>
                <div style={{ padding: "20px", borderRadius: "5px" }}>
                  <div className="d-flex justify-content-between align-items-center mb-3">
                    <h4
                      style={{
                        fontSize: "1.5rem",
                        fontWeight: "bold",
                        color: "white",
                      }}
                    >
                      RECENT REVIEWS
                    </h4>
                    <Button variant="primary" style={{ width: "30%" }}>
                      Write Review
                    </Button>
                  </div>
                  {reviews.map((review, index) => (
                    <div
                      key={index}
                      style={{
                        backgroundColor: "#2f2f2f",
                        padding: "15px",
                        marginBottom: "10px",
                        borderRadius: "5px",
                        color: "white",
                      }}
                    >
                      <p>
                        <strong>{review.name}</strong> (Verified User) -{" "}
                        {review.date}
                      </p>
                      <p>{review.review}</p>
                      <div style={{ color: "#ffcc00" }}>
                        {"⭐".repeat(review.rating)}
                      </div>
                    </div>
                  ))}
                  <Button variant="primary" style={{ width: "30%" }}>
                    Load More Reviews
                  </Button>
                </div>
              </Col>
            </Row>
          </Container>
        );

      case "Technical":
        return (
          <div style={styles.section}>
            <div className="container">
              <div className="row g-4">
                {/* System Requirements */}
                <div className="col-md-8">
                  <div style={styles.card}>
                    <h5 className="mb-4">System Requirements</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <h6>Supported Platforms</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🪟 Windows 10/11 (Web App)</li>
                          <li>🍎 macOS 11+ (Chrome or Safari)</li>
                          <li>📱 Android & iOS (Mobile Browser)</li>
                          <li>🌐 Modern browsers (Chrome, Firefox, Edge)</li>
                        </ul>
                      </div>
                      <div className="col-md-6">
                        <h6>Hardware Requirements</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>⚡ Intel i3 or equivalent (2.0 GHz+)</li>
                          <li>🧠 4 GB RAM (8 GB preferred for HD rendering)</li>
                          <li>💾 300 MB disk space for cache</li>
                          <li>📶 Stable high-speed internet (4 Mbps+)</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Resources & Support */}
                <div className="col-md-4">
                  <div style={styles.card}>
                    <h5 className="mb-4">Resources</h5>
                    <ul className="list-unstyled mb-4" style={styles.smallText}>
                      <li>📄 Getting Started with Pictory</li>
                      <li>💻 API Documentation</li>
                      <li>🎥 Video Tutorials</li>
                      <li>🎓 AI Video Academy</li>
                      <li>💬 Support Community</li>
                    </ul>
                    <h5>Support</h5>
                    <button
                      className="btn w-100 my-2"
                      style={styles.button}
                      onMouseOver={(e) => {
                        e.target.style.backgroundColor =
                          styles.buttonHover.backgroundColor;
                        e.target.style.borderColor =
                          styles.buttonHover.borderColor;
                      }}
                      onMouseOut={(e) => {
                        e.target.style.backgroundColor =
                          styles.button.backgroundColor;
                        e.target.style.borderColor = styles.button.borderColor;
                      }}
                    >
                      🎧 Contact Support
                    </button>
                    <small className="text-muted d- text-center">
                      24/7 technical support for premium users
                    </small>
                  </div>
                </div>

                {/* Integrations */}
                <div className="col-12">
                  <div style={styles.card}>
                    <h5 className="mb-4">Integration Capabilities</h5>
                    <div className="row">
                      <div className="col-md-4">
                        <h6>Content Sources</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>🧰 Google Docs</li>
                          <li>🧰 Microsoft Word</li>
                          <li>🧰 Blog URLs for video summarization</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Export Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>💻 MP4 Video Export</li>
                          <li>💻 SRT/VTT Subtitles</li>
                          <li>💻 Social media formats</li>
                        </ul>
                      </div>
                      <div className="col-md-4">
                        <h6>Marketing Tools</h6>
                        <ul className="list-unstyled" style={styles.smallText}>
                          <li>📢 Hootsuite Integration</li>
                          <li>📢 HubSpot</li>
                          <li>📢 LinkedIn & Facebook Upload</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Why-We-Use":
        return (
          <div className="container">
            <div className="row g-4">
              <div className="col-12">
                <div className="custom-card text-light p-5 text-center">
                  <h3 className="fw-bold mb-4 text-start text-primary">
                    Why <strong>XMind AI</strong> Is the Ideal Solution for
                    Efficient, Accurate, and Creative Text Enhancement
                  </h3>

                  <p className="text-start text-white mb-3">
                    <strong>XMind AI</strong> revolutionizes the way you
                    approach text rewriting, offering precision and versatility
                    without compromising quality. Whether you’re refining
                    emails, streamlining reports, or enhancing academic writing,
                    here’s why XMind AI is a top choice:
                  </p>

                  <ul
                    className="text-start"
                    style={{
                      listStyleType: "disc",
                      paddingLeft: "1.5rem",
                      fontSize: "1rem",
                      lineHeight: "1.5",
                    }}
                  >
                    <li className="mb-3">
                      <strong>Advanced Text Refinement:</strong> Perfectly
                      balances clarity and creativity, providing polished
                      content that fits your objectives.
                    </li>
                    <li className="mb-3">
                      <strong>100% Original Output:</strong> Guarantees
                      plagiarism-free results, ideal for both professional and
                      public use.
                    </li>
                    <li className="mb-3">
                      <strong>Adaptive Tone Customization:</strong>{" "}
                      Automatically adjusts text style, whether for formal
                      documents, casual conversations, or persuasive marketing
                      materials.
                    </li>
                    <li className="mb-3">
                      <strong>Fast & Efficient Editing:</strong> Produces
                      high-quality results in seconds, helping you meet tight
                      deadlines without compromising quality.
                    </li>
                    <li className="mb-3">
                      <strong>User-Friendly Interface:</strong> Designed for
                      both experts and beginners, ensuring a smooth experience
                      for everyone.
                    </li>
                    <li className="mb-3">
                      <strong>Versatility Across Contexts:</strong> Whether
                      you’re drafting emails, writing product descriptions, or
                      creating blog posts, XMind AI adapts to all your needs.
                    </li>
                  </ul>

                  <div className="text-center mt-4">
                    <button className="btn btn-primary btn-sm">
                      Try <strong>XMind AI</strong> — Transform Your Writing
                      Quickly, Clearly, and Creatively
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case "Pros & Cons":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Why <strong>XMind AI</strong> Is a Powerful and Innovative Tool
              for Efficient Content Rewriting
            </h4>
            <p className="text-center text-secondary mb-4">
              <strong>XMind AI</strong> helps streamline your writing process by
              offering enhanced rewording, clarity, and content improvement, all
              while ensuring unique and copyright-free text.
            </p>

            {/* XMind AI Section */}
            <div className="row justify-content-center gap-2 mb-5">
              {/* XMind AI Pros */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #008080",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-success text-start mb-4">
                  ✅ XMind AI - Pros
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Adaptive Writing Styles:</strong> Provides multiple
                    tone options (formal, casual, creative) to suit various
                    writing needs.
                  </li>
                  <li className="mb-2">
                    <strong>Fresh and Plagiarism-Free Content:</strong> Ensures
                    all rewritten content is original and ready for any project.
                  </li>
                  <li className="mb-2">
                    <strong>Instant Text Enhancements:</strong> Offers
                    on-the-fly improvements, from sentence structure to word
                    choice, for smoother flow.
                  </li>
                  <li className="mb-2">
                    <strong>Context-Aware Rewriting:</strong> Retains the
                    original meaning while improving clarity and engagement in
                    all types of content.
                  </li>
                  <li className="mb-2">
                    <strong>Versatile for Multiple Applications:</strong>{" "}
                    Whether you’re crafting emails, reports, or articles, XMind
                    AI adapts to a wide range of content formats.
                  </li>
                </ul>
              </div>

              {/* XMind AI Cons */}
              <div
                className="col-lg-5 col-md-6 col-sm-12"
                style={{
                  border: "1px solid #008080",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <h5 className="text-warning text-start mb-4">
                  ⚠️ XMind AI - Cons
                </h5>
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>Requires Internet Connection:</strong> Functions
                    only with online access, limiting usability in offline
                    scenarios.
                  </li>
                  <li className="mb-2">
                    <strong>Not Ideal for Creative Fiction:</strong> Primarily
                    geared towards professional, academic, and informational
                    writing rather than storytelling.
                  </li>
                  <li className="mb-2">
                    <strong>May Over-Simplify Complex Ideas:</strong> Can
                    sometimes strip away important details in technical or
                    academic content.
                  </li>
                  <li className="mb-2">
                    <strong>No In-Built Citation Support:</strong> Lacks the
                    ability to automatically cite sources, requiring users to
                    validate information for research purposes.
                  </li>
                  <li className="mb-2">
                    <strong>Advanced Features Behind a Paywall:</strong> Some
                    premium functionalities, such as batch processing, are
                    restricted to paid versions.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      case "Alternative":
        return (
          <div className="container my-5">
            <h4 className="text-center text-light mb-2">
              Explore Top Alternatives to XMind AI for Enhanced Text Rewriting
            </h4>
            <p className="text-center text-secondary mb-4">
              While <strong>XMind AI</strong> offers cutting-edge content
              rewriting with precision, several other tools offer unique
              features for text simplification, rewording, and
              summarization—each catering to different content needs and writing
              styles.
            </p>
            <div className="row justify-content-center gap-2">
              <div
                className="col-lg-8 col-md-8 col-sm-12"
                style={{
                  border: "1px solid #007bff",
                  borderRadius: "12px",
                  padding: "20px",
                  backgroundColor: "#23272b",
                  minHeight: "100%",
                }}
              >
                <ul className="ps-3" style={{ listStyleType: "disc" }}>
                  <li className="mb-2">
                    <strong>XMind AI</strong>: Delivers precise content
                    transformations by maintaining your original message while
                    adjusting tone and style to fit various writing purposes.
                  </li>
                  <li className="mb-2">
                    <strong>ClarityRewrite</strong>: Perfect for transforming
                    intricate or dense text into easy-to-understand language
                    without losing key details.
                  </li>
                  <li className="mb-2">
                    <strong>RefinePro</strong>: Specialized in rewriting
                    technical content and academic papers, it helps improve
                    clarity and structure, making complex ideas more accessible.
                  </li>
                  <li className="mb-2">
                    <strong>TextSculptor</strong>: Ideal for users needing
                    concise summaries, this tool condenses lengthy articles and
                    reports into digestible key points.
                  </li>
                  <li className="mb-2">
                    <strong>RephrasePlus</strong>: Offers a wide range of
                    rewriting options, from casual to formal, allowing users to
                    adapt content for different contexts or audiences.
                  </li>
                  <li className="mb-2">
                    <strong>ContentCraft</strong>: Tailored for content
                    creators, it optimizes copy by adjusting tone, style, and
                    structure to match brand guidelines and target audiences.
                  </li>
                  <li className="mb-2">
                    <strong>SummaryGenius</strong>: Efficiently shortens
                    reports, articles, and long-form content, making them easier
                    to skim without missing the essential message.
                  </li>
                  <li className="mb-2">
                    <strong>RewritePro</strong>: A versatile tool that offers
                    full control over the complexity, creativity, and flow of
                    your rewritten content.
                  </li>
                  <li className="mb-2">
                    <strong>TextSimplify</strong>: Ideal for breaking down
                    complicated documents—technical manuals, legal papers, and
                    more—into plain language for better understanding.
                  </li>
                  <li className="mb-2">
                    <strong>InstaSummarize</strong>: Automatically condenses
                    long paragraphs or articles into bite-sized summaries,
                    perfect for quick insights.
                  </li>
                  <li className="mb-2">
                    <strong>WriteEase</strong>: Helps users streamline content,
                    whether it's for business reports or creative writing, by
                    enhancing readability and flow.
                  </li>
                  <li className="mb-2">
                    <strong>FocusWrite</strong>: Designed for professionals,
                    this tool refines presentations, white papers, and research
                    documents, ensuring clarity and precision.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <>
      <div className="bg-dark d-flex  justify-content-between align-items-center ">
        <a
          href="/Aitools"
          className="d-inline-block text-white text-decoration-none ml-3 py-1"
        >
          <i className="bi bi-arrow-left me-2"></i>Back to Directory{" "}
        </a>
      </div>
      <div className="bg-dark text-light min-vh-100 py-5">
        <div className="container">
          <div className=" row d-flex align-items-center justify-content-between mb-1">
            {/* Left side (Text Section) */}
            <div
              style={{ flex: 1, paddingRight: "30px" }}
              className="col-6 col-md-12 "
            >
              <p className="text-primary">Write better, faster</p>
              <h1>XMind AI:</h1>
              <div className="text-warning mb-1">⭐⭐⭐⭐⭐</div>
              <p>
                XMind AI is a powerful tool that combines mind mapping with
                artificial intelligence to help individuals and teams organize,
                brainstorm, and manage tasks efficiently. Known for its visually
                engaging mind maps, XMind AI offers an intuitive platform for
                ideation, project planning, and strategic thinking. It is a
                go-to tool for creative professionals, business planners, and
                anyone looking to optimize productivity through visual thinking
                and AI-driven features.
              </p>

              <div className="mb-3">
                <span className="badge bg-primary me-2">Image Generation</span>
                <span className="badge bg-success me-2">Creative</span>
                <span className="badge bg-warning text-dark">Paid</span>
              </div>
            </div>

            {/* Right side (Image Section) */}
            <div
              style={{
                flex: 1,
                textAlign: "center",
                Width: "100%",
                height: "250px",
              }}
              className="col-6 col-md-12 mb-5  "
            >
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl5IyEpRsYY8JsmOlBNKKmWf5jlOBFs3Ustg&s"
                style={{ MaxWidth: "100%", height: "300px" }}
              />
            </div>
          </div>

          <section style={{ backgroundColor: "#2e3b4e", padding: "3rem 0" }}>
            <div className="container text-center">
              <p className="text-primary">
                Powered by Precision—Rewriting Made Effortless with XMind AI
              </p>
              <h2
                className="text-white"
                style={{ fontWeight: "600", marginBottom: "1rem" }}
              >
                Discover How XMind AI Transforms Complex Ideas into Concise,
                Tailored Content
              </h2>
              <p
                style={{
                  color: "#ccc",
                  marginBottom: "2rem",
                  fontStyle: "italic",
                }}
              >
                XMind AI allows you to refine intricate or specialized text into
                clear, accessible language—preserving your original intent while
                ensuring originality and copyright-free content.
              </p>

              <div className="row g-4">
                {/* Step 1 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .xmind-step1 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      In-Depth Content Understanding
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      XMind AI analyzes your content deeply, capturing its
                      essence and context to offer refined and precise
                      transformations that align with your goals.
                    </p>
                    <div className="xmind-step1">1</div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .xmind-step2 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Tailored Rewriting Options
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Choose from various styles and rewrite settings to meet
                      your specific needs—whether it’s for professional, casual,
                      or educational content.
                    </p>
                    <div className="xmind-step2">2</div>
                  </div>
                </div>

                {/* Step 3 */}
                <div className="col-md-4">
                  <div
                    style={{
                      position: "relative",
                      backgroundColor: "#0056b3",
                      borderRadius: "12px",
                      boxShadow: "0 2px 4px rgba(255,255,255,0.1)",
                      padding: "2rem",
                      height: "100%",
                    }}
                  >
                    <style>{`
            .xmind-step3 {
              position: absolute;
              bottom: 10px;
              right: 15px;
              font-size: 4rem;
              font-weight: bold;
              color: #a0c4f3;
              opacity: 0.6;
            }
          `}</style>
                    <h5 style={{ fontWeight: "bold", color: "#fff" }}>
                      Authentic and Ready-to-Publish Content
                    </h5>
                    <p style={{ color: "#fff", margin: 0 }}>
                      Every output generated by XMind AI is original and
                      uniquely tailored, ensuring you're always free from
                      duplication risks—ideal for any application.
                    </p>
                    <div className="xmind-step3">3</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tab Navigation */}
          <ul className="nav nav-tabs custom-tabs mb-4">
            {[
              "Features",
              "Screenshots",
              "Reviews",
              "FAQs",
              "Technical",
              "Why-We-Use",
              "Pros & Cons",
              "Alternative",
            ].map((tab) => (
              <li className="nav-item mb-2" key={tab}>
                <button
                  className={`nav-link ${activeTab === tab ? "active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              </li>
            ))}
          </ul>

          {/* Tab Content */}
          <div className="tab-content-area">{renderTabContent()}</div>

          <div className="bg-primary text-center text-light rounded-4 p-5 mt-5">
            <h4 className="mb-3">Ready to get started with XMind AI?</h4>
            <p className="mb-4">
              Join thousands of professionals already boosting their
              productivity!
            </p>
            <div>
              <button className="btn btn-light me-3">Try Now for Free</button>
              <button className="btn btn-outline-light">Schedule a Demo</button>
            </div>
            <small className="d-block mt-2">
              No credit card required. 14-day free trial available.
            </small>
          </div>
        </div>
      </div>
    </>
  );
};

export default XMind;
